# $Id: Makefile,v 1.1 2004/11/01 10:27:04 janakj Exp $
#
# Digest Authentication - Database support
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=avp_db.so
LIBS=

include ../../Makefile.modules
