#
# Makefile for the AppWeb packages
#
# Copyright (c) Mbedthis Software LLC, 2003-2004. All Rights Reserved.
#

PRE_DIRS	= $(BLD_OS)

include 	make.dep 

## Local variables:
## tab-width: 4
## End:
## vim: tw=78 sw=4 ts=4
