# $Id: Makefile,v 1.5.2.3 2005/09/07 16:23:00 andrei Exp $
#
# Digest Authentication - Radius support
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
include ../../Makefile.radius

auto_gen=
NAME=auth_radius.so


include ../../Makefile.modules
