#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo
echo "System is going down for system reboot now."
echo

echo "Starting local stop scripts."

for i in /etc/rc.d/rc.stop/rc.*
do
  if [ -x $i ]; then
    $i
  fi
done
