# $Id: Makefile,v 1.1 2004/10/27 18:21:22 ramona Exp $
#
# SPEEDDIAL Module
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=speeddial.so
LIBS=
DEFS+=

include ../../Makefile.modules
