#!/bin/bash
#
#	makeUninstall - Uninsall AppWeb 
#
#	Copyright {c} Mbedthis Software LLC, 2003-2004. All Rights Reserved.
#	The latest version of this code is available at http://www.mbedthis.com
#
#	This software is open source; you can redistribute it and/or modify it 
#	under the terms of the GNU General Public License as published by the 
#	Free Software Foundation; either version 2 of the License, or {at your 
#	option} any later version.
#
#	This program is distributed WITHOUT ANY WARRANTY; without even the 
#	implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
#	See the GNU General Public License for more details at:
#	http://www.mbedthis.com/downloads/gplLicense.html
#	
#	This General Public License does NOT permit incorporating this software 
#	into proprietary programs. If you are unable to comply with the GPL, a 
#	commercial license for this software and support services are available
#	from Mbedthis Software at http://www.mbedthis.com
#
################################################################################

. ${BLD_TOP}/config.sh

/sbin/service ${BLD_PRODUCT} stop >/dev/null 2>&1
/sbin/chkconfig --del ${BLD_PRODUCT} >/dev/null 2>&1
rm -f /etc/${BLD_PRODUCT}Install.conf
rm -f ${BLD_LIB_PREFIX}/lib${BLD_PRODUCT}*
rm -f ${BLD_SBIN_PREFIX}/${BLD_PRODUCT}
rm -f ${BLD_SBIN_PREFIX}/httpClient
rm -f ${BLD_SBIN_PREFIX}/httpPassword
rm -f ${BLD_SBIN_PREFIX}/httpComp
rm -f ${BLD_ROOT_PREFIX}/etc/rc.d/init.d/${BLD_PRODUCT}
rm -f ${BLD_ROOT_PREFIX}/etc/rc.d/rc*.d/???${BLD_PRODUCT}
rm -fr ${BLD_DOC_PREFIX}
rm -fr ${BLD_WEB_PREFIX}
rm -fr ${BLD_INC_PREFIX}
rm -fr ${BLD_SRC_PREFIX}
rm -fr ${BLD_PREFIX}
rm -fr /var/appWeb

