.TH XA60 1 "May 1991"
.SH NAME
xa60 \- A simple X11 front end for a60 (edit and go)
.SH SYNOPSIS
.B xa60
[
.B "-V"
] | [
.B "<source file>"
]
.SH DESCRIPTION
Xa60 is an simple X front end for the a60 interpreter. It offers a
window for editing the source and a second one for examining the output
from executing the source.
.br
Please remember: it is very simple.
.SH OPTIONS
.TP
.B "-V"
Print the version string and exit.
.TP
.B "<source-file>"
Use <source-file> for editing. The changes will be saved.
.SH FILES
a60 - the a60 interpreter must be in the PATH.
.SH BUGS
Currently, no input is sent to the a60 process.
.br
Only the first line number of parsing errors is set.
.SH AUTHOR
Erik Schoenfelder (schoenfr@ibr.cs.tu-bs.de)
.br
May 1991
