.TH NESSUS-BUILD 1 "November 1999" "Debian Project" "Nessus plugins"
.SH NAME
nessus-build \- build a Nessus plugin from a C source file
.SH SYNOPSIS
.B nessus-build
.I <file.c> <file.nes>
.SH DESCRIPTION
.BR nessus-build
script can be used to build a .nes Nessus plugin from a .c source file.
.SH SEE ALSO
.BR nessus (1),
.BR nessusd (8).
.SH AUTHOR
Nessus plugins, along with the rest of Nessus, are made by Renaud Deraison
<deraison@cvs.nessus.org>.
.sp
This manual page was written by Josip Rodin <jrodin@jagor.srce.hr>.
