#!/bin/sh
#
# Usally you don't need to setup any routes manually as pppd sets
# the default route automatically
#
# If you however need more than the default route, this is the syntax:
#   route add -net 10.0.0.0 netmask 255.0.0.0 gw 192.168.0.100
#
