#!/bin/sh
#
# You can either configure a PPP peer to which you dial out over the built-in
# analog modem (/dev/ttyS1) or a PPP over ethernet (PPPoE) peer
#
# Unless dial-on-demand is used, this script does not start any
# program that will dial out, it only puts the according command into
# a file (/var/ppp-connect-cmd) which is then used (e.g. by the
# connect_to_isp script) to dial out
#
# To setup your DPCM to dial out to your ISP via the built-in analog
# modem, use (this is the default):
#   echo "pppd file /etc/ppp/options_modem ttyS1 115200" >/var/ppp-connect-cmd
#
# To setup your DPCM to connect to your ISP using PPPoE via the interface
# labelled "1" (which is eth1), use:
#   echo "pppd file /etc/ppp/options_pppoe eth1" >/var/ppp-connect-cmd
#
# To use dial-on-demand (only works with the analog modem, NOT
# with PPPoE), use (DON'T FORGET the '&' sign - if you leave it out,
# your DPCM will hang on boot and you will have to reset it to
# the default configuration):
#   diald &
#
echo "pppd file /etc/ppp/options_modem ttyS1 115200" >/var/ppp-connect-cmd
