# uClibc regex tests
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.

#TESTS_DISABLED := testregexi testregexn

include ../Test.mak

CFLAGS_tst-regex2 := -std=c99

OPTS_testregex := < basic.dat
OPTS_testregexc := < categorize.dat
OPTS_testregexf := < forcedassoc.dat
OPTS_testregexi := -c < interpretation.dat
OPTS_testregexl := < leftassoc.dat
OPTS_testregexn := -c < nullsubexpr.dat
OPTS_testregexp := < repetition.dat
OPTS_testregexr := < rightassoc.dat
