.TH speedtouch-start "1" "May 2004" "SpeedTouch USB driver"
.SH NAME
speedtouch-start \- starts an ADSL connection over a SpeedTouch USB modem
.SH SYNOPSIS
.B speedtouch-start
.SH DESCRIPTION
.PP
\fBspeedtouch-start\fR starts an ADSL connection over a SpeedTouch USB or SpeedTouch 330 modem.

.SH RETURN VALUES
.TP
0 on success, any other value on failure
.SH SEE ALSO
.TP
\fBspeedtouch-setup(1)\fR, \fBspeedtouch-stop(1)\fR
.SH AUTHOR
SpeedTouch USB driver development team.
