.TH speedtouch-stop "1" "May 2004" "SpeedTouch USB driver"
.SH NAME
speedtouch-stop \- stops an ADSL connection over a SpeedTouch USB modem
.SH SYNOPSIS
.B speedtouch-stop
.SH DESCRIPTION
.PP
\fBspeedtouch-stop\fR stops an ADSL connection over a SpeedTouch USB or SpeedTouch 330 modem.

.SH RETURN VALUES
.TP
0 on success, any other value on failure
.SH SEE ALSO
.TP
\fBspeedtouch-setup(1)\fR, \fBspeedtouch-start(1)\fR
.SH AUTHOR
SpeedTouch USB driver development team.
