.rn '' }`
''' $RCSfile$$Revision$$Date$
'''
''' $Log$
'''
.de Sh
.br
.if t .Sp
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.de Ip
.br
.ie \\n(.$>=3 .ne \\$3
.el .ne 3
.IP "\\$1" \\$2
..
.de Vb
.ft CW
.nf
.ne \\$1
..
.de Ve
.ft R

.fi
..
'''
'''
'''     Set up \*(-- to give an unbreakable dash;
'''     string Tr holds user defined translation string.
'''     Bell System Logo is used as a dummy character.
'''
.tr \(*W-|\(bv\*(Tr
.ie n \{\
.ds -- \(*W-
.ds PI pi
.if (\n(.H=4u)&(1m=24u) .ds -- \(*W\h'-12u'\(*W\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(*W\h'-12u'\(*W\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
'''   \*(M", \*(S", \*(N" and \*(T" are the equivalent of
'''   \*(L" and \*(R", except that they are used on ".xx" lines,
'''   such as .IP and .SH, which do another additional levels of
'''   double-quote interpretation
.ds M" """
.ds S" """
.ds N" """""
.ds T" """""
.ds L' '
.ds R' '
.ds M' '
.ds S' '
.ds N' '
.ds T' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds M" ``
.ds S" ''
.ds N" ``
.ds T" ''
.ds L' `
.ds R' '
.ds M' `
.ds S' '
.ds N' `
.ds T' '
.ds PI \(*p
'br\}
.\"	If the F register is turned on, we'll generate
.\"	index entries out stderr for the following things:
.\"		TH	Title 
.\"		SH	Header
.\"		Sh	Subsection 
.\"		Ip	Item
.\"		X<>	Xref  (embedded
.\"	Of course, you have to process the output yourself
.\"	in some meaninful fashion.
.if \nF \{
.de IX
.tm Index:\\$1\t\\n%\t"\\$2"
..
.nr % 0
.rr F
.\}
.TH SMTPCLIENT 1 "EN" "21/Oct/97" "Ralf S. Engelschall"
.UC
.if n .hy 0
.if n .na
.ds C+ C\v'-.1v'\h'-1p'\s-2+\h'-1p'+\s0\v'.1v'\h'-1p'
.de CQ          \" put $1 in typewriter font
.ft CW
'if n "\c
'if t \\&\\$1\c
'if n \\&\\$1\c
'if n \&"
\\&\\$2 \\$3 \\$4 \\$5 \\$6 \\$7
'.ft R
..
.\" @(#)ms.acc 1.5 88/02/08 SMI; from UCB 4.2
.	\" AM - accent mark definitions
.bd B 3
.	\" fudge factors for nroff and troff
.if n \{\
.	ds #H 0
.	ds #V .8m
.	ds #F .3m
.	ds #[ \f1
.	ds #] \fP
.\}
.if t \{\
.	ds #H ((1u-(\\\\n(.fu%2u))*.13m)
.	ds #V .6m
.	ds #F 0
.	ds #[ \&
.	ds #] \&
.\}
.	\" simple accents for nroff and troff
.if n \{\
.	ds ' \&
.	ds ` \&
.	ds ^ \&
.	ds , \&
.	ds ~ ~
.	ds ? ?
.	ds ! !
.	ds /
.	ds q
.\}
.if t \{\
.	ds ' \\k:\h'-(\\n(.wu*8/10-\*(#H)'\'\h"|\\n:u"
.	ds ` \\k:\h'-(\\n(.wu*8/10-\*(#H)'\`\h'|\\n:u'
.	ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'^\h'|\\n:u'
.	ds , \\k:\h'-(\\n(.wu*8/10)',\h'|\\n:u'
.	ds ~ \\k:\h'-(\\n(.wu-\*(#H-.1m)'~\h'|\\n:u'
.	ds ? \s-2c\h'-\w'c'u*7/10'\u\h'\*(#H'\zi\d\s+2\h'\w'c'u*8/10'
.	ds ! \s-2\(or\s+2\h'-\w'\(or'u'\v'-.8m'.\v'.8m'
.	ds / \\k:\h'-(\\n(.wu*8/10-\*(#H)'\z\(sl\h'|\\n:u'
.	ds q o\h'-\w'o'u*8/10'\s-4\v'.4m'\z\(*i\v'-.4m'\s+4\h'\w'o'u*8/10'
.\}
.	\" troff and (daisy-wheel) nroff accents
.ds : \\k:\h'-(\\n(.wu*8/10-\*(#H+.1m+\*(#F)'\v'-\*(#V'\z.\h'.2m+\*(#F'.\h'|\\n:u'\v'\*(#V'
.ds 8 \h'\*(#H'\(*b\h'-\*(#H'
.ds v \\k:\h'-(\\n(.wu*9/10-\*(#H)'\v'-\*(#V'\*(#[\s-4v\s0\v'\*(#V'\h'|\\n:u'\*(#]
.ds _ \\k:\h'-(\\n(.wu*9/10-\*(#H+(\*(#F*2/3))'\v'-.4m'\z\(hy\v'.4m'\h'|\\n:u'
.ds . \\k:\h'-(\\n(.wu*8/10)'\v'\*(#V*4/10'\z.\v'-\*(#V*4/10'\h'|\\n:u'
.ds 3 \*(#[\v'.2m'\s-2\&3\s0\v'-.2m'\*(#]
.ds o \\k:\h'-(\\n(.wu+\w'\(de'u-\*(#H)/2u'\v'-.3n'\*(#[\z\(de\v'.3n'\h'|\\n:u'\*(#]
.ds d- \h'\*(#H'\(pd\h'-\w'~'u'\v'-.25m'\f2\(hy\fP\v'.25m'\h'-\*(#H'
.ds D- D\\k:\h'-\w'D'u'\v'-.11m'\z\(hy\v'.11m'\h'|\\n:u'
.ds th \*(#[\v'.3m'\s+1I\s-1\v'-.3m'\h'-(\w'I'u*2/3)'\s-1o\s+1\*(#]
.ds Th \*(#[\s+2I\s-2\h'-\w'I'u*3/5'\v'-.3m'o\v'.3m'\*(#]
.ds ae a\h'-(\w'a'u*4/10)'e
.ds Ae A\h'-(\w'A'u*4/10)'E
.ds oe o\h'-(\w'o'u*4/10)'e
.ds Oe O\h'-(\w'O'u*4/10)'E
.	\" corrections for vroff
.if v .ds ~ \\k:\h'-(\\n(.wu*9/10-\*(#H)'\s-2\u~\d\s+2\h'|\\n:u'
.if v .ds ^ \\k:\h'-(\\n(.wu*10/11-\*(#H)'\v'-.4m'^\v'.4m'\h'|\\n:u'
.	\" for low resolution devices (crt and lpr)
.if \n(.H>23 .if \n(.V>19 \
\{\
.	ds : e
.	ds 8 ss
.	ds v \h'-1'\o'\(aa\(ga'
.	ds _ \h'-1'^
.	ds . \h'-1'.
.	ds 3 3
.	ds o a
.	ds d- d\h'-1'\(ga
.	ds D- D\h'-1'\(hy
.	ds th \o'bp'
.	ds Th \o'LP'
.	ds ae ae
.	ds Ae AE
.	ds oe oe
.	ds Oe OE
.\}
.rm #[ #] #H #V #F C
.SH "NAME"
smtpclient -- simple SMTP client
.SH "SYNOPSIS"
\fBsmtpclient\fR 
[\fB\-s\fR \fISTR\fR]
[\fB\-f\fR \fIADDR\fR]
[\fB\-r\fR \fIADDR\fR]
[\fB\-e\fR \fIADDR\fR]
[\fB\-c\fR \fIADDR\fR]
[\fB\-S\fR \fIHOST\fR]
[\fB\-P\fR \fINUM\fR]
[\fB\-M\fR]
[\fB\-L\fR]
[\fB\-v\fR]
\fIrecipient\fR ...
.PP
\fBsmtpclient\fR 
[\fB\-V\fR]
[\fB\-h\fR]
.SH "VERSION"
1.0.0 (21-10-1997)
.SH "DESCRIPTION"
\fBSMTPclient\fR is a minimal SMTP client that takes an email message body and
passes it on to a SMTP server (default is the MTA on the local host). Since it
is completely self-supporting, it is especially suitable for use in restricted
environments.
.PP
A typical usage is as a MTA emulating program on a dedicated webserver.  There
it is usually called from within a CGI program to receive a mail (constructed
by the CGI program out of a HTML form) and to forward it to the actual
mailserver.
.SH "OPTIONS"
.Ip "\fB\-s\fR, \fB--subject=\fR\fI\s-1STR\s0\fR" 4
Specifies the \f(CWSubject:\fR header. This gives the message a title. Default is
no subject.
.Ip "\fB\-f\fR, \fB--from=\fR\fI\s-1ADDR\s0\fR" 4
Specifies the \f(CWFrom:\fR address header. This is the logical senders address.
Default is ``\f(CWdaemon\fR'\*(R', which is probably wrong.
.Ip "\fB\-r\fR, \fB--reply-to=\fR\fI\s-1ADDR\s0\fR" 4
Specifies the \f(CWReply-To:\fR address header. This is where replies should be
send to. Default is no such header.
.Ip "\fB\-e\fR, \fB--errors-to=\fR\fI\s-1ADDR\s0\fR" 4
Specifies the \f(CWErrors-To:\fR address header. This is where delivery
problems should be reported. Default is no such header.
.Ip "\fB\-c\fR, \fB--carbon-copy=\fR\fI\s-1ADDR\s0\fR" 4
Specifies the \f(CWCc:\fR address header. This can contain one or more addresses
(seperated by comma) to which one copy of the message is send to. Default is
no such header.
.Ip "\fB\-S\fR, \fB--smtp-host=\fR\fI\s-1HOST\s0\fR" 4
Specifies the name or \s-1IP\s0\-address of the \s-1SMTP\s0 host to connect to. This is the
host where the \s-1MTA\s0 is running to which the message is forwarded. By default,
the mail is send to the \s-1SMTP\s0 daemon on \f(CWlocalhost\fR or to the host specified
in the environment-variable \f(CWSMTPSERVER\fR if exists.
.Ip "\fB\-P\fR, \fB--smtp-port=\fR\fI\s-1NUM\s0\fR" 4
Specifies the port of the \s-1SMTP\s0 host to connect to. Default is port 25 (smtp).
.Ip "\fB\-M\fR, \fB--mime-encode\fR" 4
Use \s-1MIME\s0\-style translation to quoted-printable (base 16).
.Ip "\fB\-L\fR, \fB--use-syslog\fR" 4
Log errors to system's \fIsyslog\fR facility instead of \fIstderr\fR.
.Ip "\fB\-v\fR, \fB--verbose\fR" 4
Turn on verbose logging to \fIstdout\fR.
.Ip "\fB\-V\fR, \fB--version\fR" 4
Display the program version.
.Ip "\fB\-h\fR, \fB--help\fR" 4
Display the usage page.
.SH "RESULTS"
The program terminates with a non-zero exit status in case of errors. 
.SH "AUTHOR"
.PP
.Vb 3
\& Ralf S. Engelschall
\& rse@engelschall.com
\& www.engelschall.com
.Ve

.rn }` ''
.IX Title "SMTPCLIENT 1"
.IX Name "smtpclient - simple SMTP client"

.IX Header "NAME"

.IX Header "SYNOPSIS"

.IX Header "VERSION"

.IX Header "DESCRIPTION"

.IX Header "OPTIONS"

.IX Item "\fB\-s\fR, \fB--subject=\fR\fI\s-1STR\s0\fR"

.IX Item "\fB\-f\fR, \fB--from=\fR\fI\s-1ADDR\s0\fR"

.IX Item "\fB\-r\fR, \fB--reply-to=\fR\fI\s-1ADDR\s0\fR"

.IX Item "\fB\-e\fR, \fB--errors-to=\fR\fI\s-1ADDR\s0\fR"

.IX Item "\fB\-c\fR, \fB--carbon-copy=\fR\fI\s-1ADDR\s0\fR"

.IX Item "\fB\-S\fR, \fB--smtp-host=\fR\fI\s-1HOST\s0\fR"

.IX Item "\fB\-P\fR, \fB--smtp-port=\fR\fI\s-1NUM\s0\fR"

.IX Item "\fB\-M\fR, \fB--mime-encode\fR"

.IX Item "\fB\-L\fR, \fB--use-syslog\fR"

.IX Item "\fB\-v\fR, \fB--verbose\fR"

.IX Item "\fB\-V\fR, \fB--version\fR"

.IX Item "\fB\-h\fR, \fB--help\fR"

.IX Header "RESULTS"

.IX Header "AUTHOR"

