/* !! This file was automatically generated by NEWVERS !! */

/* for logfiles, etc. */
char SMTPclient_Version[] =
    "1.0.0 (22-10-1997)";

/* interactive 'hello' string to identify us to the user */
char SMTPclient_Hello[] = 
    "This is SMTPclient Version 1.0.0 (22-10-1997)";

/* a GNU --version output */
char SMTPclient_GNUVersion[] =
    "SMTPclient Version 1.0.0";

/* a UNIX what(1) id string */
char SMTPclient_WhatID[] =
    "@(#)SMTPclient Version 1.0.0 (22-10-1997)";

/* a RCS ident(1) id string */
char SMTPclient_RCSIdentID[] =
    "$Id: SMTPclient 1.0.0 22-10-1997 $";

/* a WWW id string */
char SMTPclient_WebID[] =
    "SMTPclient/1.0.0";

/* a plain id string */
char SMTPclient_PlainID[] =
    "1.0.0";

