#
# Purgatory ppc
#

ppc_PURGATORY_SRCS += purgatory/arch/ppc/misc.S
ppc_PURGATORY_SRCS += purgatory/arch/ppc/purgatory-ppc.c
ppc_PURGATORY_SRCS += purgatory/arch/ppc/console-ppc.c

dist += purgatory/arch/ppc/Makefile $(ppc_PURGATORY_SRCS)		\
	purgatory/arch/ppc/purgatory-ppc.h purgatory/arch/ppc/ppc_asm.h

