#
#	Makefile to build MPR for Linux
#
#	Copyright (c) Mbedthis Software LLC, 2003-2004. All Rights Reserved.
#

COMPILE			:= *.cpp
COMPILE_SHARED	:= yes
EXPORT_OBJECTS	:= yes

include 	make.dep

## Local variables:
## tab-width: 4
## End:
## vim: tw=78 sw=4 ts=4
