# Makefile for uClibc
#
# Copyright (C) 2001 by Hewlett-Packard Australia
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC := \
	mmap.c pipe.c __init_brk.c brk.c sbrk.c syscall.c pread_write.c

SSRC := setjmp.S __longjmp.S vfork.S clone.S ___fpscr_values.S

include $(top_srcdir)libc/sysdeps/linux/Makefile.commonarch
