dist += include/Makefile		\
	include/config.h		\
	include/config.h.in		\
	include/x86/x86-linux.h		\
	include/x86/mb_info.h		\
	include/x86/mb_header.h		\
	include/elf.h			\
	include/boot/linuxbios_tables.h	\
	include/boot/beoboot.h		\
	include/boot/elf_boot.h
