#ifndef __BITS_CONFNAME_H
#define __BITS_CONFNAME_H

enum {
	_SC_ARG_MAX,
#define _SC_ARG_MAX		_SC_ARG_MAX
	_SC_CHILD_MAX,
#define _SC_CHILD_MAX		_SC_CHILD_MAX
	_SC_CLK_TCK,
#define _SC_CLK_TCK		_SC_CLK_TCK
	_SC_STREAM_MAX,
#define _SC_STREAM_MAX		_SC_STREAM_MAX
	_SC_TZNAME_MAX,
#define _SC_TZNAME_MAX		_SC_TZNAME_MAX
	_SC_OPEN_MAX,
#define _SC_OPEN_MAX		_SC_OPEN_MAX
	_SC_VERSION,
#define _SC_VERSION		_SC_VERSION
	_SC_BC_BASE_MAX,
#define _SC_BC_BASE_MAX		_SC_BC_BASE_MAX
	_SC_BC_DIM_MAX,
#define _SC_BC_DIM_MAX		_SC_BC_DIM_MAX
	_SC_BC_SCALE_MAX,
#define _SC_BC_SCALE_MAX	_SC_BC_SCALE_MAX
	_SC_BC_STRING_MAX,
#define _SC_BC_STRING_MAX	_SC_BC_STRING_MAX
	_SC_COLL_WEIGHTS_MAX,
#define _SC_COLL_WEIGHTS_MAX	_SC_COLL_WEIGHTS_MAX
	_SC_EXPR_NEST_MAX,
#define _SC_EXPR_NEST_MAX	_SC_EXPR_NEST_MAX
	_SC_LINE_MAX,
#define _SC_LINE_MAX		_SC_LINE_MAX
	_SC_RE_DUP_MAX,
#define _SC_RE_DUP_MAX		_SC_RE_DUP_MAX
	_SC_2_VERSION,
#define _SC_2_VERSION		_SC_2_VERSION
	_SC_PAGESIZE,
#define _SC_PAGESIZE		_SC_PAGESIZE
#define _SC_PAGE_SIZE		_SC_PAGESIZE
	_SC_PHYS_PAGES,
#define _SC_PHYS_PAGES		_SC_PHYS_PAGES
	_SC_AVPHYS_PAGES,
#define _SC_AVPHYS_PAGES	_SC_AVPHYS_PAGES
	_SC_CHAR_BIT,
#define _SC_CHAR_BIT		_SC_CHAR_BIT
	_SC_LONG_BIT,
#define _SC_LONG_BIT		_SC_LONG_BIT
	_SC_WORD_BIT,
#define _SC_WORD_BIT		_SC_WORD_BIT
	_SC_CHAR_MAX,
#define _SC_CHAR_MAX		_SC_CHAR_MAX
	_SC_CHAR_MIN,
#define _SC_CHAR_MIN		_SC_CHAR_MIN
	_SC_INT_MAX,
#define _SC_INT_MAX		_SC_INT_MAX
	_SC_INT_MIN,
#define _SC_INT_MIN		_SC_INT_MIN
	_SC_MB_LEN_MAX,
#define _SC_MB_LEN_MAX		_SC_MB_LEN_MAX
	_SC_NZERO,
#define _SC_NZERO		_SC_NZERO
	_SC_SSIZE_MAX,
#define _SC_SSIZE_MAX		_SC_SSIZE_MAX
	_SC_SCHAR_MAX,
#define _SC_SCHAR_MAX		_SC_SCHAR_MAX
	_SC_SCHAR_MIN,
#define _SC_SCHAR_MIN		_SC_SCHAR_MIN
	_SC_SHRT_MAX,
#define _SC_SHRT_MAX		_SC_SHRT_MAX
	_SC_SHRT_MIN,
#define _SC_SHRT_MIN		_SC_SHRT_MIN
	_SC_UCHAR_MAX,
#define _SC_UCHAR_MAX		_SC_UCHAR_MAX
	_SC_UINT_MAX,
#define _SC_UINT_MAX		_SC_UINT_MAX
	_SC_ULONG_MAX,
#define _SC_ULONG_MAX		_SC_ULONG_MAX
	_SC_USHRT_MAX,
#define _SC_USHRT_MAX		_SC_USHRT_MAX
	_SC_ATEXIT_MAX,
#define _SC_ATEXIT_MAX		_SC_ATEXIT_MAX
	_SC_PASS_MAX,
#define _SC_PASS_MAX		_SC_PASS_MAX
	_SC_CHARCLASS_NAME_MAX,
#define _SC_CHARCLASS_NAME_MAX	_SC_CHARCLASS_NAME_MAX
	_SC_EQUIV_CLASS_MAX,
#define _SC_EQUIV_CLASS_MAX	_SC_EQUIV_CLASS_MAX
	_SC_JOB_CONTROL,
#define _SC_JOB_CONTROL		_SC_JOB_CONTROL
	_SC_SAVED_IDS,
#define _SC_SAVED_IDS		_SC_SAVED_IDS
	_SC_2_C_DEV,
#define _SC_2_C_DEV		_SC_2_C_DEV
	_SC_2_FORT_DEV,
#define _SC_2_FORT_DEV		_SC_2_FORT_DEV
	_SC_2_FORT_RUN,
#define _SC_2_FORT_RUN		_SC_2_FORT_RUN
	_SC_2_LOCALEDEF,
#define _SC_2_LOCALEDEF		_SC_2_LOCALEDEF
	_SC_2_SW_DEV
#define _SC_2_SW_DEV		_SC_2_SW_DEV
};

#endif /* __BITS_CONFNAME_H */
