/*
  Automatically generated by 'make config' -- don't edit!
*/
#ifndef _PCMCIA_CONFIG_H
#define _PCMCIA_CONFIG_H

#define __IN_PCMCIA_PACKAGE__

#include <linux/config.h>
#include <linux/version.h>

/*
 * Fix it all up here
 */

#endif
