.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ULOGD 8 "November 05, 2002" "Linux Netfilter"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ulogd \- netfilter/iptables ULOG daemon
.SH SYNOPSIS
.B ulogd [options]
.SH DESCRIPTION
.B ulogd
connects to the netlink device of the Linux kernel and reads messages
from the netfilter that get queued with the iptables ULOG target. For
this to work you have to compile the ULOG target into your kernel or
load the respective module.
.PP
The received messages can be logged into files or into a mySQL or
PostgreSQL database.
.SH OPTIONS
.TP
.B -d, --daemon
fork ulogd into background (start as daemon)
.TP
.B -c <filename>, --configfile <filename>
use <filename> as configuration file instead of
.I /etc/ulogd.conf
.TP
.B -h, --help
show usage information
.TP
.B -V, --version
show version information and copyright
.SH FILES
.I /etc/ulogd.conf
.br
.I /var/log/ulogd.log
.SH SEE ALSO
There is more documentation about the daemon and the database plugins
(including examples) in the directories
.nf 
.br 
.I /usr/share/doc/ulogd 
.br 
.fi
.I /usr/share/doc/ulogd-mysql
and
.nf 
.br
.I /usr/share/doc/ulogd-pgsql
.SH AUTHOR
This manual page was written by Joerg Wendland <joergland@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
