.TH LPF 8 "25 February 1999" BSD "Debian User's Guide"
.SH NAME
lpf \- lpd filter for nroff output
.SH SYNOPSIS
lpf -w width -l length
.SH DESCRIPTION
.B lpf
is a filter which reads the output of nroff and converts lines with ^H's to
overwritten lines.  Thus this works like
.BR ul (1)
but is much better: it can handle more than 2 overwrites and it is written with
some style.
.SH NOTES
This program was designed long ago, and is not much if any use today.
.SH BUGS
lpf will send itself the STOP signal when it encounters the character sequence
`\\031\\1'.
