.TH TAMAD 6 "10 JUNE 2001" TAMA "Net Tamagotchi Server"
.SH NAME
tamad \- The Net Tamagotchi server
.SH SYNOPSIS
.B tamad
.I "[port]"
.SH "DESCRIPTION"
Net Tamagotchi server - maintains multiple virtual pets on a Unix
host to be accessed through telnet.

When started, it will stay in foreground and echo all logging and
status messages to standard output, so you might want to redirect
it to a file.
.SH OPTIONS
The only option \fBtamad\fR takes is a port number to listen on. If
it is omitted, it will listen on its default port (9111).
.SH AUTHOR
Net Tamagotchi was written by Milos Glisic <mglisic@lagged.net>

This manual page was written by Gergely Nagy <algernon@debian.org>
