# Simple makefile for the hello world program

PROG    = SortedListTest
SOURCES = SortedListTest.cxx

ifndef PWLIBDIR
PWLIBDIR=$(HOME)/pwlib
endif

include $(PWLIBDIR)/make/ptlib.mak

# End of Makefile
