# Copyright (C) 1996 Robert de Bath <robert@debath.thenet.co.uk>
# This file is part of the Linux-8086 C library and is distributed
# under the GNU Library General Public License.

LIBC=../libc.a
OBJ=error.o perror.o sys_siglist.o __assert.o

all: $(LIBC)($(OBJ))
	#@$(RM) $(OBJ)

clean:
	rm -f *.o libc.a
