#!/bin/sh
#***********************************************************************
#
# go
#
# Quick-start shell script to set up ADSL
#
# Copyright (C) 2000 Roaring Penguin Software Inc.
#
# $Id: go,v 1.1.1.1 2000-11-17 05:28:42 davidm Exp $
#***********************************************************************
echo "Running ./configure..."
./configure
if [ "$?" != 0 ] ; then
    echo "Oops!  It looks like ./configure failed."
    exit 1
fi

echo "Running make..."
make
if [ "$?" != 0 ] ; then
    echo "Oops!  It looks like make failed."
    exit 1
fi

echo "Running make install..."
make install

if [ "$?" != 0 ] ; then
    echo "Oops!  It looks like make install failed."
    exit 1
fi

for i in a a a a a a a a a a a a a a a a a a a a a a a a a a a a ; do
    echo ""
done

sh ./adsl-setup
