.TH TAMA 6 "10 JUNE 2001" TAMA "Net Tamagotchi Client"
.SH NAME
tama \- The Net Tamagotchi client
.SH SYNOPSIS
.B tama
.I [host] [\-\-host <host>] [\-\-port <port>]
.SH DESCRIPTION
Connects to a given Net Tamagotchi Server running on a given
host (\fIlocalhost\fR by default).
.SH OPTIONS
The \fBtama\fR program takes the following options:
.TP
.B \-\-host <host>
Connect to \fI<host>\fR instead of the default \fIlocalhost\fR.
.TP
.B \-\-port <port>
Connect to a given host, on port \fI<port>\fR instead of \fI9111\fR.
.TP
.B <host>
Connect to \fI<host>\fR. Same as \fI\-\-host <host>\fR.
.SH AUTHOR
This manual page was written by Gergely Nagy <algernon@debian.org>
