#!/bin/sh
hostname LinuxBox
ifconfig lo 127.0.0.1
route add -net 127.0.0.0 netmask 255.0.0.0 lo
ifconfig eth0 hw ether 00:50:DD:00:4E:60
ifconfig eth0 172.27.26.200 netmask 255.255.0.0
route add default gw 172.27.0.4
#dhcpcd -p -a eth0 &
cat /etc/motd
cd /home/apli
./mfc3loader
