.TH ELVIS-TINY 1 "May 13, 1997" "" "Debian GNU/Linux Manual"
.SH NAME
elvis-tiny \- Tiny vi-compatible editor
.SH DESCRIPTION
Elvis-tiny is a very small vi-compatible editor with limited
capabilities. If you want more features (and documentation), install
its big brother \fBelvis\fP or any of the other vi clones such as
\fBnvi\fP or \fPvim\fP.
.SH "SEE ALSO"
ae(1).
