#! /bin/sh

case "$1" in
	configure)
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
		;;
esac
umask 022

update-alternatives --install /usr/bin/vi vi /usr/bin/elvis-tiny 10 \
  --slave /usr/man/man1/vi.1.gz vi.1.gz /usr/man/man1/elvis-tiny.1.gz

