.TH g3toxwd 1 "22 may 94" "Chel" "mgetty+sendfax manual"
.IX g3toxwd
.SH NAME
g3toxwd \- converts a Group 3 fax file into a displayable xwd file
.SH SYNOPSIS
.B g3toxwd
.RB [ -kludge ]
.RB [ -reversebits ]
.RB [ -scale\ N ]
.RB [ -aspect\ N ]
.RB [ -skiprows\ N ]
.RB [ -name\ xwdname ]
.RI [ g3file ]
.SH DESCRIPTION
Reads a Group 3 fax file (raw or digifax) as input. If no filename is
given, stdin is used.
.IX "Group 3 fax"
.IX fax
Produces a displayable xwd file as output.
.SH OPTIONS
.TP
.B -kludge
Tells
.I g3toxwd
to skip the first lines for synchronisation.
.TP
.B -reversebits
Tells
.I g3toxwd
to interpret bits least-significant
first, instead of the default most-significant first.
Apparently some fax modems do it one way and others do it the other way.
If you get a whole bunch of "invalid code" messages, try using this
flag.
.TP
.B -scale N
Scale the output to match the printer resolution and paper size, the default
of 0.58 will do in most cases.
.TP
.B -aspect N
Scale the output to match the printer resolution and paper size, the default
of 1.0 will do for high resolution faxes, 2.0 will do for low resolution faxes.
.TP
.B -skiprows N
N faxrows of the input file will be skipped.
.TP
.B -name <name>
The name <name> will be put in the output file for xwd.
.TP
.SH REFERENCES
The standard for Group 3 fax is defined in CCITT Recommendation T.4.
.SH BUGS
Long fax files are not handled properly.
Output size fixed 1000x1350 pixels defined at compile time.
Please report bugs to chel@vangennip.nl
.SH "SEE ALSO"
pbmtog3(1), pbm(5), g3cat(1), sendfax(8), mgetty(1)
.SH AUTHOR
.I g3toxwd
is Copyright (C) 1994 by Chel van Gennip, <chel@vangennip.nl>. Sources of 
.I g3topbm
and
.I pbmtoxwd
programs in Jef Poskanzers
.I pbmplus
package have been used, but al lot of code has been changed or added to 
simplify its use for displaying faxes. Value added: low use of memory, fast 
scaling.
