#
# Makefile for the bootstrap directory  
#
# Copyright (c) Mbedthis Software LLC, 2003-2004. All Rights Reserved.
#

include 	make.dep

PRE_DIRS	= bldout genDepend

ifeq	($(BLD_OS),WIN)
POST_DIRS	= dumpext
endif

## Local variables:
## tab-width: 4
## End:
## vim: tw=78 sw=4 ts=4
