# $Id: Makefile,v 1.1 2003/10/23 15:27:29 calrissian Exp $
#
# opt_rpl module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=options.so
LIBS=

include ../../Makefile.modules
