# $Id: Makefile,v 1.3 2003/11/05 11:49:25 janakj Exp $
#
# registrar module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=registrar.so
LIBS=

DEFS+=-I../.. -I../usrloc

include ../../Makefile.modules
