.\"                                      Hey, EMACS: -*- nroff -*-
.TH ARJ 1 2003-04-18 "3.10" "Arj Software"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
arj \- Archiver for .arj files
.SH SYNOPSIS
.B arj
.I command
.RI [ -switch [ - | + | option ]]
.IR archive [ .arj ]
.RI [ "base directory" ]
.RI [ "!list name" | "path name" | "wildcard name" ]
.SH COMMANDS
.TP
.B ac
Add Chapter to chapter archive.
.TP
.B cc
Convert archive to Chapter archive.
.TP
.B dc
Delete last Chapter from archive.
.TP
.B a
Add files to archive.
.TP
.B b
execute Batch or dos command.
.TP
.B c
Comment archive files.
.TP
.B d
Delete files from archive.
.TP
.B e
Extract files from archive.
.TP
.B f
Freshen files in archive.
.TP
.B g
Garble files in archive.
.TP
.B i
check Integrity of the \fBarj\fP program.
.TP
.B j
Join archives to archive
.TP
.B k
remove obsolete bacKup files.
.TP
.B l
List contents of archive.
.TP
.B m
Move files to archive.
.TP
.B n
reName files in archive.
.TP
.B o
Order files in archive.
.TP
.B p
Print files to standard output.
.TP
.B q
recover damaged \fBarj\fP file.
.TP
.B r
Remove paths from filenames.
.TP
.B s
Sample files to screen with pause.
.TP
.B t
Test integrity of archive.
.TP
.B u
Update files to archive.
.TP
.B v
Verbosely list contents of archive.
.TP
.B w
Where are text strings in archive.
.TP
.B x
eXtract files with full pathname.
.TP
.B y
copY archive with new options.
.SH SWITCHES
.TP
.B c
skip time-stamp Check
.TP
.B e
Exclude paths from names
.TP
.B f
Freshen existing files
.TP
.B g
Garble with password
.TP
.B i
with no progress Indicator
.TP
.B m
with Method 0, 1, 2, 3, 4
.TP
.B n
only New files (not exist)
.TP
.B r
Recurse subdirectories
.TP
.B u
Update files (new and newer)
.TP
.B v
enable multiple Volumes
.TP
.B w
assign Work directory
.TP
.B x
eXclude selected files
.TP
.B y
assume Yes on all queries
.TP
.B hk
enable ARJ-PROTECT damage protection
.SH DETAILED SWITCHES
.TP
.B -
Disables switch char
.TP
.B +
Inhibits ARJ_SW usage
.RS
+var: set environment variable
.RE
.TP
.B @
Set 1 token per response file line
.TP
.B !
Set list char (!)
.TP
.B &
Set batch critical error handler
.TP
.B #
Select files by number
.TP
.B $
Add/extract volume label
.RS
$A: add/extract label to drive A
.RE
.TP
.B a
Allow any file Attribute
.RS
a1: any files, directories and UNIX special files
.RE
.TP
.B b
Backup changed files
.nf
.RS
b1: Backup changed, reset archive bits
b2: only reset archive bits
b3: reset archive bit during restore
b4: do not restore bits, reset arc
b5: do not restore any file attributes
.RE
.fi
.TP
.B c
Skip time-stamp Check
.TP
.B d
Delete added files asks permission before deleting
.nf
.RS
d1: Delete without permission (same as \fBarj m\fP)
d2: Truncate instead of deleting
.RE
.fi
.TP
.B e
Exclude paths from names
.RS
e1: Exclude base dir from names
.RE
.TP
.B f
Freshen existing files
.nf
.RS
f1: Freshen with OLDER files
f2: Freshen with DIFFERENT files
f3: Freshen with CRC mismatched files
.RE
.fi
.TP
.B g
Garble with password
.nf
.RS
g\fIstew\fP: garble with password stew
g?: prompt for password
.RE
.fi
.TP
.B i
Show no progress Indicator
.nf
.RS
i1: show bar graph Indicator
i2: show percentage and bar graph
i3: total progress percentage
i4: total progress bar graph
i5: total percentage and bar graph
i6: total percentage and file graph
.RE
.fi
.TP
.B k
Keep a .bak of \fBarj\fP archive
.TP
.B l
Create List_name file
.RS
l\fInames.list\fP: create \fInames.list\fP
.RE
.TP
.B m
With Method 0, 1, 2, 3, 4
.nf
.RS
m0: store (no compression)
m1: good compression (default)
m2: less memory and compression
m3: FAST! less compression
m4: FASTEST! least compression
.RE
.fi
.TP
.B n
Only New files (not exist)
.TP
.B o
On or after YYYYMMDDHHMMSS
.nf
.RS
o:       on today
o19901225: on/after 12/25/1990
ob: Before YYYYMMDDHHMMSS
ob:       before today
ob19901225: before 12/25/1990
od: no older than N Days
od5: five or less days old
oa: After YYYYMMDDHHMMSS (last access)
oa:       on today
oa19901225: after 12/25/1990
oab: Before YYYYMMDDHHMMSS (last access)
oab:      before today
oab19901225: before 12/25/1990
oc: After YYYYMMDDHHMMSS (created)
oc:       on today
oc19901225: after 12/25/1990
ocb: Before YYYYMMDDHHMMSS
ocb:      before today
ocb19901225: before 12/25/1990
.RE
.fi
.TP
.B p
Match using full Pathnames
.RS
p1: match Pathname with subdirs
.RE
.TP
.B q
Query on each file
.TP
.B r
Recurse subdirectories
.TP
.B s
Set archive time-Stamp to newest
.nf
.RS
s1: save original time-Stamp
s2: set archive time-Stamp
s3: save both original time-Stamps
.RE
.fi
.TP
.B t
Set file Type (default 0)
.nf
.RS
t0: set binary file type
t1: set C text file type
t1f: force C text file type
t1g: set C text with graphics
.RE
.fi
.TP
.B u
Update files (new + newer)
.nf
.RS
u1: Update files (new + OLDER)
u2: Update files (new + different)
u3: Update files (new + CRC mismatch)
.RE
.fi
.TP
.B v
Enable multiple Volumes
.nf
.RS
v360: build 362000 byte volumes
v50K: build 50000 byte volumes
va: auto-detect space available
vd\fI/tmp/*\fP: delete \fI/tmp/*\fP
ve: use alternate volume naming
vi: inhibit diskette change test
vr50K: reserve 50000 bytes of space on first volume
vs: provide command prompt
vs\fBcmd\fP: execute \fBcmd\fP before each vol
vv: beep between volumes
vw: keep Whole files in volumes
vz: provide command with no echo
v360,v720,v1200,v1440: abbrevs Volume options may be in any order
       except s and z which must be last
.RE
.fi
.TP
.B w
Assign Work directory
.RS
w\fI/tmp\fP: use \fI/tmp\fP as work directory
.RE
.TP
.B x
eXclude selected files
.nf
.RS
x\fI*.sh\fP: exclude \fI*.sh\fP files
x!\fInames\fP: exclude files in \fInames\fP multiple exclusions are allowed
.RE
.fi
.TP
.B y
Assume Yes on all queries except diskette volume prompts
    Use this switch for batch mode
.TP
.B z
Supply archive comment file
.B _
Convert filenames to lower case
.nf
.RS
z\fIarc.cmt\fP: use \fIarc.cmt\fP for comments
z\fI/dev/null\fP: use to strip comments
.RE
.fi
.SH SHIFTED SWITCHES
.TP
.B h#
Append date string to name
.nf
.RS
h#1: append time string to name
h#2: append DHHMMSS to name (custom: h#{Y,M,D,N,h,m,s})
h#YYYY-MMDD: append YYYY-MMDD
.RE
.fi
.TP
.B h$
Try to use longnames (Win2000)
.TP
.B h2
Obsolete synonym for -2 group of options
.TP
.B ha
Ignore readonly Attribute
.TP
.B hb
Select by file attribute/type
.nf
.RS
a - archive bit set
b - archive bit clear
r - readonly
s - system
h - hidden
d - directory
n - normal file, not d,h,r,s,c,l
c - chapter label
l - volume label
f - abbrev for n,d,r,s,h
u - UNIX special files
w - win95 long filenames
hb: select all types
hbsh: select hidden, system only
hbd: select dirs only
.RE
.fi
.TP
.B hc
Execute Command at \fBarj\fP start
.RS
hc\fBclear\fP: execute \fBclear\fP
.RE
.TP
.B he
Skip test of security Envelope
.RS
he1: set error on security Envelope
.RE
.TP
.B hf
Set short filenames only
.nf
.RS
hf1: set longnames in file comment or extract with \fIw95lname.nnn\fP
hf2: use long filenames in DOS
hf3: set longnames in file comment using shortname wildcards
hf4: set all files archived in Windows as Windows long filenames
.RE
.fi
.TP
.B hg
Specify garble module filename
.nf
.RS
hg\fIarjcrypt.so\fP: set \fIarjcrypt.so\fP as name of garble module
hg!: specify use of 40 bit encryption
.RE
.fi
.TP
.B hi
Detailed display in Index files
.TP
.B hk
Build data protection record
.TP
.B hk
Default amount of recovery data
.nf
.RS
hk1: more recovery data
hk9: maximum amount of recovery data
     Disable ARJ-PROTECT when used with the \fB"y"\fP command
.RE
.fi
.TP
.B hl
Return error for Listfile error
.TP
.B hm
Increase file list capacity
.nf
.RS
hm!: redirect -hm temp file
hm! : move temp file to XMS mem
hm!\fI/tmp\fP : move temp file to \fI/tmp\fP
.RE
.fi
.TP
.B hn
Specify non-existent filespec
.RS
hn\fB####\fP: set \fB####\fP as filespec
.RE
.TP
.B ho
Only extract files with matches
.RS
ho1: Only extract files without matches
.RE
.TP
.B hq
Ignore open access error on adds
.nf
.RS
hq1: ignore open not found error on adds
hq2: ignore access and not found on adds
.RE
.fi
.TP
.B hr
Try to ignore archive errors
.TP
.B hs
Disable file Sharing
.TP
.B ht
Set Target directory
.RS
ht\fI/destdir\fP
.RE
.TP
.B hu
Allow Update of volume archives
.TP
.B hv
Check for \fBarj\fP version
.TP
.B hw
Scroll save search filename display
.RS
hw1: display only filenames with matches
.RE
.TP
.B hx
Set default archive extensions
.RS
hx\fI.arj.sdn\fP
.RE
.TP
.B hy
set \fBarj32\fP to use ANSI codepage
set \fBarj\fP to extract ANSI codepage archive
.nf
.RS
hy1: force \fBarj32\fP to use OEM codepage
hy2: force \fBarj32\fP to use ANSI codepage
.RE
.fi
.TP
.B hz
Create an ARJ-SECURITY envelope
.TP
.B j#
Store only CRC and not the file
.nf
.RS
j#1: store only date, size, attributes
j#2: restore file attributes
j#3: restore file dates
j#4: restore file attributes and dates
.RE
.fi
.TP
.B j$
Do not process file DTA and DTC
.TP
.B ja
Set P command to display ANSI
.RS
ja1: inhibit the display of comments
.RE
.TP
.B jb
Set chapter backup processing
.nf
.RS
jb0: clear chapter archive status
jb*: select all chapter backup files
.RE
.fi
.TP
.B jc
Exit after Count of files
.nf
.RS
jc5: exit after 5 files
jc \fInam1 nam2\fP: exit after 2 files
.RE
.fi
.TP
.B jd
Ensure free Disk space
.nf
.RS
e -jd\fI50K\fP: skip file if<\fI50000\fP free
l -jd\fI1000\fP: set error if<\fI1000\fP free
.RE
.fi
.TP
.B je
Create self-extracting archive
.RS
je1: create SFXJR archive
.RE
.TP
.B jf
Store/use Full specified path
.RS
jf1: store/use path minus drive
.RE
.TP
.B jg
[OBSOLETE]
.RS
jg1: [OBSOLETE]
.RE
.TP
.B jh
Set Huffman buffer size
.nf
.RS
jh\fI65535\fP: set to \fI65535\fP bytes (max)
jh\fI2048\fP: set to \fI2048\fP bytes (min)
.RE
.fi
.TP
.B ji
Create Index file
.RS
ji\fIindex.file\fP: create \fIindex.file\fP
.RE
.TP
.B jk
Keep temp archive on error
.TP
.B jl
Display only filespecs
.TP
.B jm
Set Maximum compression mode
.RS
jm1: set faster Maximum compression
.RE
.TP
.B jn
Restart volumes at fileName
.nf
.RS
jn\fI/bin/test\fP: restart at \fI/bin/test\fP
jn: get restart information from previously written index file
.RE
.fi
.TP
.B jo
Query when updating archive file
.nf
.RS
jo: extract to unique Output names
jo1: extract to unique Output names keeping file extension
.RE
.fi
.TP
.B jp
Pause after each screenful
.RS
jp\fI50\fP: pause, set page size to \fI50\fP
.RE
.TP
.B jq
Set string parameter
.RS
jq\fIstring\fP: set parameter to \fIstring\fP
.RE
.TP
.B jr
Recover broken archive files
.RS
jr1: Recover badly broken archive files
.RE
.TP
.B js
Store archives by suffix (default is arj, arc, lzh, pak, rar, zip, zoo, j,
and uc2).
.RS
js\fI.zoo\fP: store only \fI.zoo\fP files
.RE
.TP
.B jt
Test temporary archive by CRC
.nf
.RS
jt1: Test CRC and file contents
jt2: Test only added file contents
jt3: Test only file date-time and size
.RE
.fi
.TP
.B ju
Translate UNIX style paths
.TP
.B jv
Set Verbose display
.RS
jv1: set special verbose list mode
.RE
.TP
.B jw
Set extract output filename
.RS
jw\fInew.file\fP: output to \fInew.file\fP
.RE
.TP
.B jx
Start at eXtended position
.RS
jx\fI10000\fP: start at position 10000
.RE
.TP
.B jy
Suppress queries assuming Yes
.nf
.RS
a - skip append query
c - skip create directory query
d - skip delete files query
k - skip disk space available query
n - skip new filename prompt
o - skip overwrite file query
r - erase all type-ahead before query
s - skip scanned enough text query
v - skip proceed to next volume query
y - accept single character Y/N/A/Q
jycny: skip create, new name queries in single character
        input mode
.RE
.fi
.TP
.B jz
Supply file for file comment
.nf
.RS
jz\fIfile.cmt\fP: use \fIfile.cmt\fP for comments
jz\fI/dev/null\fP: use to strip file comments
.RE
.fi
.TP
.B 2a
Serialize names on extraction
.TP
.B 2c
[OS/2, NT] handle Crit. EAs only
.TP
.B 2d
\fBarj\fP/DOS compatibility mode
.RS
2d1: (OBSOLETE) comment compatibility
.RE
.TP
.B 2e
[OS/2, NT] filter Extended attrs
.nf
.RS
2e.*: pack/unpack system EAs only
2e.ICON?: pack/unpack icons only
2e: disable EAs handling
.RE
.fi
.TP
.B 2f
Disable comment serialization across multiple volumes
.TP
.B 2h
[UNIX] Disable hardlink handling
.RS
2h1: Extract hardlinks as symlinks
.RE
.TP
.B 2k
Skip century display in dates
.RS
2k1: use a non-ambigous date display format
.RE
.TP
.B 2l
[OS/2, NT] treat .LONGNAME EAs as filenames when possible
.TP
.B 2o
[UNIX] store/restore file ownership
.RS
2o1: Store numeric UID/GID values
2o2: Same as -2o but saves group as well
.RE
.TP
.B 2p
Specify process Priority class
.nf
.RS
OS/2, NT: 2p1...2p4
Linux, FreeBSD: 2p1...2p41
.RE
.fi
.TP
.B 2r
Revert directory Recursion order
.TP
.B 2s
[UNIX] preserve Symlink properties
.TP
.B 2x
[OS/2, NT]: eXclude extended attrs
.RS
2x.ICON?: ignore icons
.RE
.SH DEFAULTS
.nf
Save path information in archive
Save long filenames
Save/restore extended attributes
Save/restore file date-time created and accessed in Win95 and OS/2
Save timestamps in the UNIX format under UNIX-like operating systems
Don't save drive and root in path information
Display comment ANSI sequences with built-in display handler
Prompt before overwriting output files
Use method 1 compression
Use binary mode
Use ! as list file symbol
The \fB"ac"\fP command is an abbreviation for \fB"u -u2 -jb"\fP
The \fB"cc"\fP command is an abbreviation for \fB"y -jb"\fP
The \fB"dc"\fP command is an abbreviation for \fB"d -jb"\fP
.fi
.PP
Under Win32, \fBarj\fP uses OEM codepage by default.  The \fB"-hy"\fP option
sets \fBarj\fP to use the ANSI codepage which is the Windows graphical environment
default.
\fBarj\fP/Win32 self-extracting archives should be built using the \fB"-hy"\fP
option.
.PP
To ensure compatibility with previous versions of \fBarj\fP, the \fB"-2d"\fP
parameter has to be specified when archiving under UNIX.
.SH USER PROMPT RESPONSES
.TP
.B Yes
yes
.TP
.B No
no
.TP
.B Quit
abort out of \fBarj\fP
.TP
.B Always
always assume yes for current type of query
.TP
.B Skip
always assume no for current type of query
.TP
.B Global
always assume yes for all queries except diskette volume prompts
.TP
.B Command
prompt for and execute one system command
.SH ENVIRONMENT
\fBARJ_SW\fP = \fB-jyry -jv -i1\fP
.br
\fBARJ_SW\fP = \fI/etc/arj.cfg\fP
.SH EXIT STATUS
.TP
.B 0
Success
.TP
.B 1
Warning (specified file to add to archive not found, specified file to list,
extract, etc., not found, or answering negatively to "OK to proceed to next
volume..." prompt)
.TP
.B 2
Fatal error
.TP
.B 3
CRC error (header or file CRC error or bad password)
.TP
.B 4
ARJ-SECURITY error or attempt to update an ARJ-SECURED archive
.TP
.B 5
Disk full or write error
.TP
.B 6
Cannot open archive or file
.TP
.B 7
Simple user error (bad parameters)
.TP
.B 8
Not enough memory
.TP
.B 9
Not an \fBarj\fP archive
.TP
.B 10
[DOS] XMS memory error (read or write)
.TP
.B 11
User control break
.TP
.B 12
Too many chapters (over 250)
.SH EXAMPLES
.TP
Add files minus directory structure:
\fBarj\fP a -e archive *
.TP
Add two files to archive:
\fBarj\fP a archive \fIname1 name2\fP
.TP
Add files to archive with verification:
\fBarj\fP a -jt archive *
.TP
Add files with maximum compression:
\fBarj\fP a -jm archive *
.TP
Add several directories of files:
\fBarj\fP a archive ... \fIdir1 dir2 dir3\fP
.TP
Add thousands of files to an archive:
\fBarj\fP a -hm1 -r archive *
.TP
Add a chapter to an archive:
\fBarj\fP ac archive \fI/foo/dir/*\fP -r
.TP
Comment archive header only:
\fBarj\fP c archive -z\fIcmt.fil\fP
.TP
Convert standard archive to chapter:
\fBarj\fP cc archive
.TP
Convert chapter archive to standard:
\fBarj\fP y archive -jb0
.TP
Delete the last chapter from an archive:
\fBarj\fP dc archive *
.TP
Strip archive comment only:
\fBarj\fP c archive -z\fI/dev/null\fP
.TP
Extract files from archive:
\fBarj\fP e archive
.TP
Extract maintaining directory structure:
\fBarj\fP x archive
.TP
Extract new and newer files without query:
\fBarj\fP e archive -u -y
.TP
Extract subdirectory from archive:
\fBarj\fP e archive \fIsubdir/*\fP -p1
.TP
Extract files to directory:
\fBarj\fP x archive \fIdestdir/\fP *
.TP
Extract files to directory:
\fBarj\fP x archive * -htdestdir
.TP
Extract files to directory with space:
\fBarj\fP x archive "\fISome Dir/ \fP"
.TP
Extract files to directory with space:
\fBarj\fP x archive "-ht\fISome Dir\fP"
.TP
Extract a Win95 archive to plain DOS:
\fBarj\fP x archive -hf2
.TP
List files in archive:
\fBarj\fP l archive
.TP
Move files to archive:
\fBarj\fP m archive \fI*.tex\fP
.TP
Move files from archive:
\fBarj\fP e -d archive \fI*.tex\fP
.TP
Recover files from a damaged archive:
\fBarj\fP x archive -jr
.TP
Test integrity of files in archive:
\fBarj\fP t archive
.TP
Test multiple \fBarj\fP archives:
\fBarj\fP t \fI*.arj\fP -hr
.TP
Add files to a multiple volume archive:
\fBarj\fP a -va \fI/floppy/archive\fP *
.TP
Create up to 999 archive volumes:
\fBarj\fP a -va \fI/floppy/archive.001\fP
.TP
Extract from a multiple volume archive:
\fBarj\fP x -v \fI/floppy/archive\fP
.TP
Create a multiple volume self-extractor:
\fBarj\fP a -va -je \fI/floppy/archive\fP *
.TP
Convert archive to self-extractor:
\fBarj\fP y -je1 archive
.TP
Backup dir \fI/foo\fP to dir \fI/floppy\fP:
\fBarj\fP a \fI/floppy/backup\fP \fI/foo\fP -a1 -b2 -r -vvas -w\fI/foo\fP -js -jt -hk
.TP
Restore backup on dir \fI/floppy\fP to dir \fI/foo\fP:
\fBarj\fP x \fI/floppy/backup\fP \fI/foo\fP -vv -y
.SH SELF-EXTRACTOR ARCHIVES
If the first two characters of an \fBarj\fP comment are "\fB))\fP" in a
self-extractor, then the self-extractor will accept the appended line
as its command line.
.PP
"\fB)) -o\fP"
will force the self-extractor to overwrite existing files.
.SH SEE ALSO
.BR rearj (1),
.BR unarj (1),
.BR arj-register (1).
.SH AUTHOR
This manual page was written by Ola Lundqvist <opal@debian.org> in pod format,
then converted by Guillem Jover <guillem@debian.org> to nroff format.
