.\"                                      Hey, EMACS: -*- nroff -*-
.TH REARJ 1 2003-03-10 "3.10" "Arj Software"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
rearj \- Converts other archive formats to .arj files
.SH SYNOPSIS
.B rearj
.RI [ options ]
.RI < !listfile(s) | filespec(s) | wildname(s) >
.SH DESCRIPTION
The
.B rearj
command can repackage other archive formats to arj.
.SH OPTIONS
.TP
.B \-+
Ignore REARJ_SW variable.
.TP
.BI \-a [suffix]
Convert archives within archives ("*" for all formats).
.TP
.BI \-b command
Execute command before extracting files.
.TP
.BI \-c command
Execute command on extracted files before counting them.
.TP
.B \-d
Delete original archives.
.TP
.B \-e
No error switch.
.TP
.B \-f
Convert diskette archives.
.TP
.B \-g
Skip creation of output archive.
.TP
.BI \-i [name]
Check integrity of
.I rearj
program.
.TP
.B \-j
Skip if output archive size is larger than the original.
.TP
.B \-k
Skip archive timestamping.
.TP
.BI \-l [name]
Write append log file (default name is
.IR rearj.log ).
.TP
.BI \-m [date]
Select archives before date in
.I YYMMDDHHMMSS
format.
.TP
.BI \-n [date]
Select archives on or after date in
.I YYMMDDHHMMSS
format.
.TP
.B \-o
Allow overwrite of existing target archive.
.TP
.B \-p
Ignore long filenames under Windows 95.
.TP
.B \-q
Query for each archive to convert.
.TP
.B \-r
Recurse through subdirectories.
.TP
.B \-s
Skip verify of file count and total size.
.TP
.BI \-t suffix
Create suffix type archives.
.TP
.BI \-u [bak]
Allow update of archive with backup (default is
.IR BAK ).
.TP
.B \-v
Execute configured command on extracted files.
.TP
.BI \-w dir
Assign work directory.
.TP
.BI \-x [!]file
Exclude by filename, wildname, or listfile.
.TP
.BI \-y [text]
Delete output archive and write text to log (testing mode).
.TP
.B \-z
Simulate operation.
.SH ENVIRONMENT
.B REARJ_SW
If set, its value will be used as command line options.
.SH "EXIT STATUS"
.TP
.BR 0
Success.
.TP
.BR 1
File not found.
.TP
.BR 2
File is not a configured archive type.
.TP
.BR 3
Target archive already exists.
.TP
.BR 4
Not enough disk space.
.TP
.BR 5
User skipped or user did not select update option.
.TP
.BR 6
UNPACK command error.
.TP
.BR 7
PACK command error.
.TP
.BR 8
Target cannot support directories.
.TP
.BR 9
Wrong file count.
.TP
.BR 10
Wrong total size.
.TP
.BR 11
Internal archive REARJ error.
.TP
.BR 12
Rename archive error.
.TP
.BR 13
Invoked \-v command error (found a virus?).
.TP
.BR 14
Output archive is larger.
.SH EXAMPLE
.TP
.B rearj * \-r \-d
Convert all archives to \fBARJ\fP format, searching all subdirectories,
deleting original archives.
.SH SEE ALSO
.BR arj (1).
.SH AUTHOR
This manual page was written by Ola Lundqvist <opal@debian.org> in pod format,
then converted by Guillem Jover <guillem@debian.org> to nroff format.

