#!/bin/sh

ledctl 2 2

rm -f /var/ppp-status
echo PPP interface name: $1 >>/var/ppp-status
echo Used device: $2 >>/var/ppp-status
# $3 (speed) is the tty line speed which is uninteresting (always 115200)
echo Local IP address: $4 >>/var/ppp-status
echo Remote IP address: $5 >>/var/ppp-status
