# Author : Benoit PAPILLAULT <benoit.papillault@free.fr
# Creation : 21/02/2002

default: check-hdlc check-hdlc-bug

check-hdlc: check-hdlc.o
check-hdlc-bug: check-hdlc-bug.o

check-hdlc-bug.o: check-hdlc-bug.c
check-hdlc.o: check-hdlc.c

