# Makefile for uClibc
#
# Copyright (C) 2000-2005 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC := brk.c __syscall_error.c

SSRC := \
	__longjmp.S fork.S vfork.S clone.S setjmp.S bsd-setjmp.S bsd-_setjmp.S \
	syscall.S urem.S udiv.S umul.S sdiv.S rem.S

include $(top_srcdir)libc/sysdeps/linux/Makefile.commonarch
