.\" Copyright (c) 2000 Benjamin C. Reed <breed@almaden.ibm.com>
.\" airo_cs.c.4
.\"
.TH AIRO_CS 4 "1/17/00" "IBM Almaden Research Center"

.SH NAME
airo_cs \- PCMCIA Services wrapper for Aironet PC4500&4800 cards and Cisco 340 PCMCIA cards

.SH SYNOPSIS
.B insmod airo_cs.o

.SH DESCRIPTION
.B airo_cs
is the adapter to the 
.B airo
driver for Aironet PC4500 & PC4800 802.11 and Cisco 340 
wireless ethernet cards.
This driver must be loaded after
.BR airo (4).
It handles the events from Card Services since
.B airo
is not Card Services aware.

.SH PARAMETERS

None.

.SH AUTHOR
Benjamin C. Reed \- breed@almaden.ibm.com

.SH SEE ALSO
.BR airo (4),
.BR cardmgr (8),
.BR pcmcia (5),
.BR insmod (1),
