y.\" Copyright (c) 1996 Shingo Fujimoto <shingo@flab.fujitsu.co.jp>
.\" fmvj18x_cs.4,v 1.4 1999/02/08 08:02:01 root Exp
.\"
.TH FMVJ18x_CS 4 "1999/02/08 08:02:01" ""
.SH NAME
fmvj18x_cs \- Fujitsu FMV-J18x series device driver
.SH SYNOPSIS
.B insmod fmvj18x_cs.o
.RB [ pc_debug=\c
.IR n ]
.RB [ fmvj18x_debug=\c
.IR n ]
.RB [ irq_list=\c
.IR i,j,... ]
.SH DESCRIPTION
.B fmvj18x_cs
is the low-level Card Services driver for the Fujitsu FMV-J18x
series PCMCIA ethernet adapter.  When this driver is attached to a card, it
allocates the next available ethernet device
.RB ( eth0 .. eth# ).
This
device name will be reported in the kernel log file, and passed on to
.BR cardmgr (8).
.SH PARAMETERS
.TP
.BI pc_debug= n
Selects the PCMCIA debugging level.  This parameter is only available
if the module is compiled with debugging enabled.  A non-zero value
enables debugging.
.TP
.BI fmvj18x_debug= n
Selects the network debugging level.  The current default is 3; values
of up to six increase reporting verbosity.
.TP
.BI irq_list= i,j,...
Specifies the set of interrupts that may be allocated by this driver.
.SH AUTHOR
Shingo Fujimoto \- Fujitsu Laboratories Ltd.
<Shingo@flab.fujitsu.co.jp>
.SH THANKS
.TP 
Yutaka TAMIYA \- Fujitsu Laboratories Ltd.
.TP 
Hideaki Yoda \- Fujitsu Limited.
.SH "SEE ALSO"
cardmgr(8), pcmcia(5).
