.\" Copyright (C) 1998 David A. Hinds -- dahinds@users.sourceforge.net
.\" ftl_check.1 1.7 2000/06/12 21:24:48
.\"
.TH FTL_CHECK 1 "2000/06/12 21:24:48" "pcmcia-cs"
.SH NAME
ftl_check \- Flash Translation Layer format checker
.SH SYNOPSIS
.B ftl_check
.I device
.SH DESCRIPTION
.B Ftl_check
dumps a lot of bookkeeping information for a Flash Translation Layer
partition.  It needs to access the flash partition's raw character-mode
device (such as
.IR /dev/mem0c0c ).
It cannot actually fix formatting problems.
.SH AUTHOR
David Hinds \- dahinds@users.sourceforge.net
.SH "SEE ALSO"
ftl_format(8).
