.\" Copyright (C) 1998 David A. Hinds -- dahinds@users.sourceforge.net
.\" ide_info.8 1.6 2000/06/12 21:24:48
.\"
.TH IDE_INFO 8 "2000/06/12 21:24:48" "pcmcia-cs"
.SH NAME
ide_info \- IDE device description tool
.SH SYNOPSIS
.B ide_info
.I device
.SH DESCRIPTION
.B Ide_info
opens the specified IDE device file, and retrieves its device
identification information.  Its
output is a set of Bourne-style shell commands to define the
.BR MODEL ,
.BR FW_REV ,
and
.B SERIAL_NO
variables based on this information.  The PCMCIA configuration script
for IDE-type devices uses this utility so that the serial number can
be used to specify configurations for particular cards.
.SH AUTHOR
David Hinds \- dahinds@users.sourceforge.net
