.\" Copyright (C) 1998 David A. Hinds -- dahinds@users.sourceforge.net
.\" ifuser.8 1.6 2000/06/12 21:24:48
.\"
.TH IFUSER 8 "2000/06/12 21:24:48" "pcmcia-cs"
.SH NAME
ifuser \- identify destinations routed to a particular network interface
.SH SYNOPSIS
.B ifuser
.RB [ -v ]
.I interface
.RI [ "target\ ..." ]
.SH DESCRIPTION
This utility checks to see if any of the listed hosts or network
addresses are routed through the specified interface.  Destinations
may be specified either by IP address or by name.
.PP
The exit code will be 0 if any listed host or network is routed
through this interface, and 1 if the interface is not in use (similar
to 
.BR fuser ).
.SH OPTIONS
.TP
.B \-v
Verbose mode: if enabled, then the names of those destinations routed
to this interface (if any) will be reported on standard output.
.SH AUTHORS
David Hinds \- dahinds@users.sourceforge.net
.br
Regis "HPReg" Duchesne \- regis@via.ecp.fr
