.\" Copyright (C) 1998 David A. Hinds -- dahinds@users.sourceforge.net
.\" scsi_info.8 1.7 2000/06/12 21:24:49
.\"
.TH SCSI_INFO 8 "2000/06/12 21:24:49" "pcmcia-cs"
.SH NAME
scsi_info \- SCSI device description tool
.SH SYNOPSIS
.B scsi_info
.I device
.SH DESCRIPTION
.B Scsi_info
opens the specified SCSI device file, and retrieves its
actual SCSI address parameters.  It also looks up the device in
.I /proc/scsi/scsi
and retrieves the device's vendor information, if available.  Its
output is a pair of Bourne-style shell commands to define the
.B SCSI_ID
and
.B MODEL
variables based on this information.  The
.B SCSI_ID
variable has three comma-separated fields: the SCSI channel number,
the device ID, and the logical unit number.  In most cases, the
channel and logical unit will be 0.
.PP
The reason for the existence of this utility lies in the peculiar
method for assigning minor device numbers to Linux SCSI devices.
Devices are numbered based on the order in which they are detected,
irrespective of their device addresses.  This tool automatically
converts these arbitrary device assignments back to the
user-configured addresses.
.SH AUTHOR
David Hinds \- dahinds@users.sourceforge.net
