.\" Copyright (C) 1998 David A. Hinds -- dahinds@users.sourceforge.net
.\" stab.5 1.13 2000/06/12 21:24:48
.\"
.TH STAB 5 "2000/06/12 21:24:48" "pcmcia-cs"
.SH NAME
stab \- current PCMCIA socket status

.SH DESCRIPTION
The \fIstab\fR file is created by \fBcardmgr\fR
and contains identification and device driver information for PCMCIA
cards.  Each socket is described by one header line, followed by one
or more device driver lines.  The header gives the card name as given
in \fI/etc/pcmcia/config\fR.
Device driver lines consist of a series of tab-separated fields.  The
first field is the socket number.  The second field is the device
class, which identifies which script in \fI/etc/pcmcia\fR
is used to configure or shut down this device.
The third field is the driver name.
The fourth field is used to number devices when a single
card has several devices associated with the same driver.  The fifth
field is the device name, and the final two fields are major and minor
device numbers for this device, if appropriate.
.PP
The file is updated by \fBcardmgr\fR whenever a card is inserted or
ejected, and when \fBcardmgr\fR receives a \fBSIGHUP\fR signal.
.PP
The \fIstab\fR file will normally be created in \fI/var/lib/pcmcia\fR,
but if that directory is unavailable, it will be found in
\fI/var/run\fR.

.SH AUTHOR
David Hinds \- dahinds@users.sourceforge.net
.SH "SEE ALSO"
cardmgr(8), pcmcia(5), cardinfo(1).
