.\" Copyright (c) 1997 Werner Koch <werner.koch@guug.de>
.\" xirc2ps_cs.4,v 1.5 1998/09/15 12:40:59 wk Exp
.\"
.TH XIRC2PS_CS 4 "1.5  1998/09/15 12:40:59" ""
.SH NAME
xirc2ps_cs \- Xircom CE2ps (and newer) device driver

.SH SYNOPSIS
.B insmod xirc2ps_cs.o
.RB [ pc_debug=\c
.IR n ]
.RB [ full_duplex=\c
.IR n ]
.RB [ irq_list=\c
.IR i,j,... ]
.RB [ if_port=\c
.IR n ]
.RB [ lockup_hack=\c
.IR n ]

.SH DESCRIPTION
\fBxirc2ps_cs\fR is the low-level Card Services driver for the Xircom
16-bit PCMCIA ethernet adapters.  When this driver is attached to a
card, it allocates the next available ethernet device.

.SH PARAMETERS
.TP
.BI pc_debug= n
Selects the PCMCIA debugging level.  This parameter is only available
if the module is compiled with debugging enabled.  A non-zero value
enables debugging.
.TP
.BI if_port= n
Selects the transceiver type, for some CE3B-100 cards that lack the
ability to autonegotiate.  For such cards, a value of 1 selects
10baseT, and 4 selects 100baseT.
.TP
.BI full_duplex= n
Selects full duplex mode.  The default is 0 (half duplex).
.TP
.BI irq_list= i,j,...
Specifies the set of interrupts that may be allocated by this driver.
.TP
.BI lockup_hack= n
Enables a hack to avoid lockups on some cards.	Use this only if you
really have lockup problems with your card.

.SH "SEE ALSO"
cardmgr(8), pcmcia(5).
.SH BUGS
Please report to <xircom-bugs@isil.d.shuttle.de>
.SH AUTHOR
Werner Koch
<werner.koch@guug.de>
