#
# Automatically generated make config: don't edit
#

#
# Core Applications
#
# CONFIG_USER_INIT_INIT is not set
# CONFIG_USER_INIT_CONSOLE_SH is not set
# CONFIG_USER_INIT_RUN_FIREWALL is not set
# CONFIG_USER_SASH_SH is not set
# CONFIG_USER_SH_SH is not set
# CONFIG_USER_NWSH_SH is not set
CONFIG_USER_BASH_BASH=y
# CONFIG_USER_OTHER_SH is not set
# CONFIG_USER_SASH_HISTORY is not set
# CONFIG_USER_SASH_REBOOT is not set
# CONFIG_USER_SASH_SHUTDOWN is not set
CONFIG_USER_INIT_EXPAND=y
# CONFIG_USER_INIT_EXPAND_NOZEROES is not set
# CONFIG_USER_VERSION_VERSION is not set
# CONFIG_USER_LOGIN_LOGIN is not set
# CONFIG_USER_AGETTY_AGETTY is not set
CONFIG_USER_GETTYD_GETTYD=y
# CONFIG_USER_LOGIN_PASSWD is not set
# CONFIG_USER_CRON_CRON is not set

#
# Flash Tools
#
CONFIG_USER_FLASHW_FLASHW=y
CONFIG_USER_NETFLASH_NETFLASH=y
# CONFIG_USER_RECOVER_RECOVER is not set
# CONFIG_USER_NETFLASH_WITH_FTP is not set
CONFIG_USER_NETFLASH_VERSION=y
# CONFIG_USER_NETFLASH_VERSION_ALLOW_CURRENT is not set
# CONFIG_USER_NETFLASH_VERSION_ALLOW_OLDER is not set
CONFIG_USER_NETFLASH_DECOMPRESS=y
CONFIG_LIB_ZLIB=y
CONFIG_USER_NETFLASH_AUTODECOMPRESS=y
# CONFIG_USER_NETFLASH_HMACMD5 is not set
# CONFIG_USER_BOOTTOOLS_FLASHLOADER is not set
# CONFIG_USER_BOOTTOOLS_HIMEMLOADER is not set

#
# MTD utils
#
# CONFIG_USER_MTDUTILS is not set
# CONFIG_USER_MTDUTILS_ERASE is not set
# CONFIG_USER_MTDUTILS_ERASEALL is not set
# CONFIG_USER_MTDUTILS_FTL_CHECK is not set
# CONFIG_USER_MTDUTILS_FTL_FORMAT is not set
# CONFIG_USER_MTDUTILS_NFTLDUMP is not set
# CONFIG_USER_MTDUTILS_NFTL_FORMAT is not set
# CONFIG_USER_MTDUTILS_NANDDUMP is not set
# CONFIG_USER_MTDUTILS_NANDTEST is not set
# CONFIG_USER_MTDUTILS_NANDWRITE is not set
# CONFIG_USER_MTDUTILS_DOC_LOADBIOS is not set

#
# Real Time Clock
#
# CONFIG_USER_HWCLOCK_HWCLOCK is not set
# CONFIG_USER_RTC_M41T11 is not set
# CONFIG_USER_RTC_DS1302 is not set

#
# Vixie-cron
#
# CONFIG_USER_VIXIECRON_CRON is not set
# CONFIG_USER_VIXIECRON_CRONTAB is not set

#
# at
#
# CONFIG_USER_AT_AT is not set
# CONFIG_USER_AT_ATD is not set
# CONFIG_USER_AT_ATRUN is not set

#
# Force library building (Normally built when required)
#
# CONFIG_LIB_LIBDES_FORCE is not set
# CONFIG_LIB_LIBSSL_FORCE is not set
# CONFIG_LIB_LIBGMP_FORCE is not set
# CONFIG_LIB_LIBG_FORCE is not set
# CONFIG_LIB_LIBPAM_FORCE is not set
# CONFIG_LIB_LIBPCAP_FORCE is not set
# CONFIG_LIB_ZLIB_FORCE is not set
# CONFIG_LIB_LIBATM_FORCE is not set
# CONFIG_LIB_LIBPNG_FORCE is not set
# CONFIG_LIB_LIBJPEG_FORCE is not set
# CONFIG_LIB_NCURSES_FORCE is not set
# CONFIG_LIB_UC_LIBC_TIMEZONE is not set

#
# Filesystem Applications
#
CONFIG_USER_FLATFSD_FLATFSD=y
# CONFIG_USER_FLATFSD_USE_FLASH_FS is not set
# CONFIG_USER_MOUNT_MOUNT is not set
# CONFIG_USER_MOUNT_UMOUNT is not set
# CONFIG_USER_FDISK_FDISK is not set

#
# EXT2
#
# CONFIG_USER_E2FSPROGS_E2FSCK_E2FSCK is not set
# CONFIG_USER_E2FSPROGS_MISC_MKE2FS is not set
# CONFIG_USER_E2FSPROGS_MISC_BADBLOCKS is not set
# CONFIG_USER_E2FSPROGS_MISC_CHATTR is not set
# CONFIG_USER_E2FSPROGS_MISC_DUMPE2FS is not set
# CONFIG_USER_E2FSPROGS_MISC_E2LABEL is not set
# CONFIG_USER_E2FSPROGS_MISC_FSCK is not set
# CONFIG_USER_E2FSPROGS_MISC_LSATTR is not set
# CONFIG_USER_E2FSPROGS_MISC_MKLOST_FOUND is not set
# CONFIG_USER_E2FSPROGS_MISC_TUNE2FS is not set
# CONFIG_USER_E2FSPROGS_MISC_UUIDGEN is not set

#
# RESIERFS
#
# CONFIG_USER_REISERFSPROGS is not set
# CONFIG_USER_REISERFSPROGS_DEBUGRESIERFS is not set
# CONFIG_USER_REISERFSPROGS_MKREISERFS is not set
# CONFIG_USER_REISERFSPROGS_REISERFSCK is not set
# CONFIG_USER_REISERFSPROGS_RESIZE_REISERFS is not set
# CONFIG_USER_REISERFSPROGS_UNPACK is not set

#
# SAMBA
#
# CONFIG_USER_SAMBA is not set
# CONFIG_USER_SAMBA_SMBD is not set
# CONFIG_USER_SAMBA_NMBD is not set
# CONFIG_USER_SAMBA_SMBMOUNT is not set
# CONFIG_USER_SAMBA_SMBUMOUNT is not set

#
# SMBFS
#
# CONFIG_USER_SMBMOUNT_SMBMOUNT is not set
# CONFIG_USER_SMBMOUNT_SMBUMOUNT is not set
# CONFIG_USER_CRAMFS_CRAMFSCK is not set
# CONFIG_USER_CRAMFS_MKCRAMFS is not set

#
# Network Applications
#
# CONFIG_USER_ROUTE_ARP is not set
CONFIG_USER_BOA_SRC_BOA=y
# CONFIG_USER_BOA_WITH_SSL is not set
CONFIG_USER_BPALOGIN_BPALOGIN=y
# CONFIG_USER_BR2684CTL_BR2684CTL is not set
# CONFIG_USER_BRCFG_BRCFG is not set
# CONFIG_USER_DHCPCD_DHCPCD is not set
CONFIG_USER_DHCPCD_NEW_DHCPCD=y
# CONFIG_USER_DHCPD_DHCPD is not set
CONFIG_USER_DHCP_ISC_SERVER_DHCPD=y
# CONFIG_USER_DHCP_ISC_CLIENT_DHCP is not set
CONFIG_USER_DIALD_DIALD=y
CONFIG_USER_DISCARD_DISCARD=y
CONFIG_USER_DNSMASQ_DNSMASQ=y
# CONFIG_USER_ETHATTACH_ETHATTACH is not set
# CONFIG_USER_EZIPUPDATE_EZIPUPDATE is not set
CONFIG_USER_FTP_FTP_FTP=y
CONFIG_USER_FREESWAN=y
CONFIG_USER_IPSEC_CONFIGURATOR=y
CONFIG_USER_FREESWAN_PLUTO_PLUTO=y
CONFIG_LIB_LIBGMP=y
CONFIG_LIB_LIBDES=y
CONFIG_USER_FREESWAN_PLUTO_WHACK=y
CONFIG_USER_FREESWAN_UTILS_RANBITS=y
CONFIG_USER_FREESWAN_UTILS_RSASIGKEY=y
CONFIG_LIB_LIBGMP=y
CONFIG_USER_FREESWAN_KLIPS_EROUTE=y
CONFIG_USER_FREESWAN_KLIPS_KLIPSDEBUG=y
CONFIG_USER_FREESWAN_KLIPS_SPI=y
CONFIG_USER_FREESWAN_KLIPS_SPIGRP=y
CONFIG_USER_FREESWAN_KLIPS_TNCFG=y
# CONFIG_USER_FSWCERT_FSWCERT is not set
# CONFIG_USER_HTTPD_HTTPD is not set
# CONFIG_USER_IDB_IDB is not set
# CONFIG_USER_IFATTACH_IFATTACH is not set
# CONFIG_USER_ROUTE_IFCONFIG is not set
# CONFIG_USER_IFMOND_IFMOND is not set
# CONFIG_USER_NEWIFMOND_IFMOND is not set
CONFIG_USER_INETD_INETD=y
CONFIG_USER_IPCHAINS_IPCHAINS=y
# CONFIG_USER_IPFWADM_IPFWADM is not set
CONFIG_USER_IPMASQADM_IPMASQADM=y
# CONFIG_USER_IPPORTFW_IPPORTFW is not set
# CONFIG_USER_IPREDIR_IPREDIR is not set
# CONFIG_USER_IPROUTE2 is not set
# CONFIG_USER_IPTABLES_IPTABLES is not set
# CONFIG_USER_KLAXON_KLAXON is not set
# CONFIG_USER_SMTP_SMTPCLIENT is not set
# CONFIG_USER_MAIL_MAIL_IP is not set
# CONFIG_USER_MARADNS_MARADNS is not set
# CONFIG_USER_MINI_HTTPD_MINI_HTTPD is not set
# CONFIG_USER_L2TPD_L2TPD is not set
# CONFIG_USER_LOATTACH_LOATTACH is not set
# CONFIG_USER_MSNTP_MSNTP is not set
# CONFIG_USER_ROUTE_NETSTAT is not set
# CONFIG_USER_NETSTAT_NAT_NETSTAT_NAT is not set
# CONFIG_USER_MARADNS_ZONESERVER is not set
# CONFIG_USER_ROUTE_MIITOOL is not set
CONFIG_USER_PING_PING=y
# CONFIG_USER_PLUG_PLUG is not set
# CONFIG_USER_PORTMAP_PORTMAP is not set
CONFIG_USER_PPPD_PPPD_PPPD=y
# CONFIG_USER_PPPD_WITH_MPPE is not set
# CONFIG_USER_PPPD_WITH_TACACS is not set
# CONFIG_USER_PPPD_WITH_RADIUS is not set
# CONFIG_USER_PPPD_WITH_PPPOE is not set
CONFIG_USER_PPTPD_PPTPCTRL=y
CONFIG_USER_PPTPD_PPTPD=y
CONFIG_USER_PPTP_CLIENT_PPTP=y
CONFIG_USER_PPTP_CLIENT_PPTP_CALLMGR=y
# CONFIG_USER_RDATE_RDATE is not set
# CONFIG_USER_MGMT_MGMT is not set
# CONFIG_USER_SGSNMPD_AGENT is not set
# CONFIG_USER_SGSNMPD_SNAPGEAR is not set
# CONFIG_USER_SGSNMPD_SG100 is not set
# CONFIG_USER_REDIALER_REDIALER is not set
# CONFIG_USER_ROUTE_ROUTE is not set
CONFIG_USER_ROUTED_ROUTED=y
CONFIG_USER_RP_PPPOE_PPPOE=y
# CONFIG_USER_SETHDLC_SETHDLC is not set
# CONFIG_USER_SLATTACH_SLATTACH is not set
# CONFIG_USER_SNMPD_SNMPD is not set
# CONFIG_USER_SNORT_SNORT is not set
# CONFIG_USER_STUNNEL_STUNNEL is not set
# CONFIG_USER_SQUID_SQUID is not set
# CONFIG_USER_SSH_SSH is not set
# CONFIG_USER_SSH_SSHD is not set
# CONFIG_USER_SSH_SSHKEYGEN is not set
CONFIG_LIB_LIBSSL=y
CONFIG_LIB_LIBSSL=y
# CONFIG_USER_STP_STP is not set
# CONFIG_USER_TCPWRAP_TCPD is not set
# CONFIG_USER_TCPBLAST_TCPBLAST is not set
CONFIG_USER_TCPDUMP_TCPDUMP=y
CONFIG_LIB_LIBPCAP=y
CONFIG_USER_TELNETD_TELNETD=y
# CONFIG_USER_TELNET_TELNET is not set
# CONFIG_USER_TFTP_TFTP is not set
# CONFIG_USER_TFTPD_TFTPD is not set
# CONFIG_USER_THTTPD_THTTPD is not set
CONFIG_USER_TRACEROUTE_TRACEROUTE=y
# CONFIG_USER_NETSNMP_SNMPD is not set
# CONFIG_USER_UPNPD is not set
# CONFIG_USER_VPNLED_VPNLED is not set
# CONFIG_USER_WGET is not set
# CONFIG_USER_WINSD_WS is not set
# CONFIG_USER_ZEBRA_ZEBRA_ZEBRA is not set

#
# Net-tools
#
CONFIG_USER_NET_TOOLS_ARP=y
# CONFIG_USER_NET_TOOLS_HOSTNAME is not set
CONFIG_USER_NET_TOOLS_IFCONFIG=y
# CONFIG_USER_NET_TOOLS_NAMEIF is not set
CONFIG_USER_NET_TOOLS_NETSTAT=y
# CONFIG_USER_NET_TOOLS_PLIPCONFIG is not set
# CONFIG_USER_NET_TOOLS_RARP is not set
CONFIG_USER_NET_TOOLS_ROUTE=y
# CONFIG_USER_NET_TOOLS_SLATTACH is not set
CONFIG_USER_NET_TOOLS_MII_TOOL=y

#
# Wireless-tools
#
# CONFIG_USER_WIRELESS_TOOLS is not set

#
# Miscellaneous Applications
#
# CONFIG_USER_LANG_A60 is not set
# CONFIG_USER_CAL_CAL is not set
CONFIG_USER_CHAT_CHAT=y
# CONFIG_USER_CKSUM_CKSUM is not set
# CONFIG_USER_CLOCK_CLOCK is not set
# CONFIG_USER_CPU_CPU is not set
# CONFIG_USER_CAL_DATE is not set
# CONFIG_USER_DESTEST_DESTEST is not set
# CONFIG_USER_DESTEST_DESPERF is not set
# CONFIG_USER_DHRYSTONE_DHRYSTONE is not set
# CONFIG_USER_FACTORY_FACTTEST is not set
# CONFIG_USER_FROB_LED_FROB_LED is not set
# CONFIG_USER_GDBSERVER_GDBREPLAY is not set
# CONFIG_USER_GDBSERVER_GDBSERVER is not set
CONFIG_USER_GDSD_GDSD=y
CONFIG_LIB_LIBSNAPGEARPP=y
# CONFIG_USER_GDSD_GDSD_INET is not set
CONFIG_USER_HD_HD=y
# CONFIG_USER_LCD_LCD is not set
# CONFIG_USER_LEDCON_LEDCON is not set
# CONFIG_USER_LILO_LILO is not set
# CONFIG_USER_LISSA_LISSA is not set
# CONFIG_USER_MATH_TEST is not set
CONFIG_USER_MAWK_AWK=y
# CONFIG_USER_NULL_NULL is not set
# CONFIG_USER_PALMBOT_PALMBOT is not set
# CONFIG_USER_PCMCIA_CS is not set
# CONFIG_USER_PERL_PERL is not set
# CONFIG_USER_PYTHON_PYTHON is not set
# CONFIG_USER_READPROFILE_READPROFILE is not set
# CONFIG_USER_ROOTLOADER_ROOTLOADER is not set
# CONFIG_USER_SETSERIAL_SETSERIAL is not set
# CONFIG_USER_TRIPWIRE_SIGGEN is not set
# CONFIG_USER_STRACE_STRACE is not set
# CONFIG_USER_STTY_STTY is not set
# CONFIG_USER_TCSH_TCSH is not set
# CONFIG_USER_THREADDEMOS_THREADDEMOS is not set
CONFIG_USER_TIP_TIP=y
# CONFIG_USER_TRIPWIRE_TRIPWIRE is not set

#
# LIRC
#
# CONFIG_USER_LIRC is not set
# CONFIG_USER_LIRC_LIRCD is not set
# CONFIG_USER_LIRC_IRRECORD is not set
# CONFIG_USER_LIRC_LIRCMD is not set
# CONFIG_USER_LIRC_IREXEC is not set
# CONFIG_USER_LIRC_IRW is not set
# CONFIG_USER_LIRC_MODE2 is not set

#
# Editors
#
# CONFIG_USER_LEVEE_VI is not set
# CONFIG_USER_ELVISTINY_VI is not set

#
# Audio tools
#
# CONFIG_USER_MP3PLAY_MP3PLAY is not set
# CONFIG_USER_OGGPLAY_OGG123 is not set
# CONFIG_USER_OGGPLAY_EXAMPLE is not set
# CONFIG_USER_SETKEY_SETKEY is not set
# CONFIG_USER_MUSICBOX_MUSICBOX is not set
# CONFIG_USER_PLAY_PLAY is not set
# CONFIG_USER_PLAY_TONE is not set
# CONFIG_USER_VPLAY_VPLAY is not set
# CONFIG_USER_VPLAY_VREC is not set
# CONFIG_USER_VPLAY_MIXER is not set
# CONFIG_USER_PLAYRT_PLAYRT is not set
# CONFIG_USER_W3CAM_VIDCAT is not set
# CONFIG_USER_W3CAM_W3CAMD is not set

#
# Fileutils tools
#
# CONFIG_USER_FILEUTILS_CAT is not set
# CONFIG_USER_FILEUTILS_CHGRP is not set
# CONFIG_USER_FILEUTILS_CHMOD is not set
# CONFIG_USER_FILEUTILS_CHOWN is not set
# CONFIG_USER_FILEUTILS_CMP is not set
# CONFIG_USER_FILEUTILS_CP is not set
# CONFIG_USER_FILEUTILS_DD is not set
# CONFIG_USER_FILEUTILS_GREP is not set
# CONFIG_USER_FILEUTILS_L is not set
# CONFIG_USER_FILEUTILS_LN is not set
# CONFIG_USER_FILEUTILS_LS is not set
# CONFIG_USER_FILEUTILS_MKDIR is not set
# CONFIG_USER_FILEUTILS_MKFIFO is not set
# CONFIG_USER_FILEUTILS_MKNOD is not set
# CONFIG_USER_FILEUTILS_MORE is not set
# CONFIG_USER_FILEUTILS_MV is not set
# CONFIG_USER_FILEUTILS_RM is not set
# CONFIG_USER_FILEUTILS_RMDIR is not set
# CONFIG_USER_FILEUTILS_SYNC is not set
# CONFIG_USER_FILEUTILS_TOUCH is not set

#
# Shutils tools
#
# CONFIG_USER_SHUTILS_BASENAME is not set
# CONFIG_USER_SHUTILS_DATE is not set
# CONFIG_USER_SHUTILS_DIRNAME is not set
# CONFIG_USER_SHUTILS_ECHO is not set
# CONFIG_USER_SHUTILS_FALSE is not set
# CONFIG_USER_SHUTILS_LOGNAME is not set
# CONFIG_USER_SHUTILS_PRINTENV is not set
# CONFIG_USER_SHUTILS_PWD is not set
# CONFIG_USER_SHUTILS_TRUE is not set
# CONFIG_USER_SHUTILS_UNAME is not set
# CONFIG_USER_SHUTILS_WHICH is not set
# CONFIG_USER_SHUTILS_WHOAMI is not set
# CONFIG_USER_SHUTILS_YES is not set

#
# Sysutils tools
#
# CONFIG_USER_SYSUTILS_REBOOT is not set
# CONFIG_USER_SYSUTILS_SHUTDOWN is not set
# CONFIG_USER_SYSUTILS_DF is not set
# CONFIG_USER_SYSUTILS_FREE is not set
# CONFIG_USER_SYSUTILS_HOSTNAME is not set
# CONFIG_USER_SYSUTILS_KILL is not set
# CONFIG_USER_SYSUTILS_PS is not set

#
# Procps tools
#
# CONFIG_USER_PROCPS_FREE is not set
# CONFIG_USER_PROCPS_KILL is not set
# CONFIG_USER_PROCPS_PGREP is not set
# CONFIG_USER_PROCPS_PKILL is not set
# CONFIG_USER_PROCPS_PS is not set
# CONFIG_USER_PROCPS_SNICE is not set
# CONFIG_USER_PROCPS_SYSCTL is not set
# CONFIG_USER_PROCPS_TLOAD is not set
# CONFIG_USER_PROCPS_TOP is not set
# CONFIG_USER_PROCPS_UPTIME is not set
# CONFIG_USER_PROCPS_VMSTAT is not set
# CONFIG_USER_PROCPS_W is not set
# CONFIG_USER_PROCPS_WATCH is not set

#
# PCI utilities
#
# CONFIG_USER_PCIUTILS_LSPCI is not set
# CONFIG_USER_PCIUTILS_SETPCI is not set

#
# BusyBox
#
CONFIG_USER_BUSYBOX_BUSYBOX=y

#
# Applets
#
# CONFIG_USER_BUSYBOX_ADJTIMEX is not set
# CONFIG_USER_BUSYBOX_AR is not set
CONFIG_USER_BUSYBOX_BASENAME=y
CONFIG_USER_BUSYBOX_CAT=y
CONFIG_USER_BUSYBOX_CHGRP=y
CONFIG_USER_BUSYBOX_CHMOD=y
CONFIG_USER_BUSYBOX_CHOWN=y
# CONFIG_USER_BUSYBOX_CHROOT is not set
CONFIG_USER_BUSYBOX_CLEAR=y
CONFIG_USER_BUSYBOX_CMP=y
CONFIG_USER_BUSYBOX_CP=y
CONFIG_USER_BUSYBOX_CUT=y
CONFIG_USER_BUSYBOX_DATE=y
# CONFIG_USER_BUSYBOX_DC is not set
CONFIG_USER_BUSYBOX_DD=y
CONFIG_USER_BUSYBOX_DF=y
CONFIG_USER_BUSYBOX_DIRNAME=y
CONFIG_USER_BUSYBOX_DMESG=y
# CONFIG_USER_BUSYBOX_DUTMP is not set
CONFIG_USER_BUSYBOX_DU=y
CONFIG_USER_BUSYBOX_ECHO=y
CONFIG_USER_BUSYBOX_ENV=y
CONFIG_USER_BUSYBOX_EXPR=y
CONFIG_USER_BUSYBOX_FIND=y
CONFIG_USER_BUSYBOX_FIND_TYPE=y
CONFIG_USER_BUSYBOX_FIND_PERM=y
CONFIG_USER_BUSYBOX_FIND_MTIME=y
# CONFIG_USER_BUSYBOX_FREE is not set
# CONFIG_USER_BUSYBOX_FREERAMDISK is not set
# CONFIG_USER_BUSYBOX_FSCK_MINIX is not set
CONFIG_USER_BUSYBOX_GETOPT=y
CONFIG_USER_BUSYBOX_GREP=y
# CONFIG_USER_BUSYBOX_GREP_CONTEXT is not set
# CONFIG_USER_BUSYBOX_GREP_EGREP_ALIAS is not set
# CONFIG_USER_BUSYBOX_GUNZIP is not set
# CONFIG_USER_BUSYBOX_GZIP is not set
# CONFIG_USER_BUSYBOX_HALT is not set
CONFIG_USER_BUSYBOX_HEAD=y
CONFIG_USER_BUSYBOX_HOSTNAME=y
CONFIG_USER_BUSYBOX_ID=y
# CONFIG_USER_BUSYBOX_IFCONFIG is not set
CONFIG_USER_BUSYBOX_INIT=y
CONFIG_USER_BUSYBOX_USE_INITTAB=y
# CONFIG_USER_BUSYBOX_LINUXRC is not set
# CONFIG_USER_BUSYBOX_INIT_COREDUMPS is not set
CONFIG_USER_BUSYBOX_INSMOD=y
# CONFIG_USER_BUSYBOX_INSMOD_LOADINKMEM is not set
CONFIG_USER_BUSYBOX_KILL=y
CONFIG_USER_BUSYBOX_KILLALL=y
CONFIG_USER_BUSYBOX_KLOGD=y
# CONFIG_USER_BUSYBOX_LENGTH is not set
CONFIG_USER_BUSYBOX_LN=y
CONFIG_USER_BUSYBOX_LOGGER=y
# CONFIG_USER_BUSYBOX_LOGNAME is not set
CONFIG_USER_BUSYBOX_LS=y
CONFIG_USER_BUSYBOX_LS_USERNAME=y
CONFIG_USER_BUSYBOX_LS_TIMESTAMPS=y
CONFIG_USER_BUSYBOX_LS_FILETYPES=y
CONFIG_USER_BUSYBOX_LS_SORTFILES=y
CONFIG_USER_BUSYBOX_LS_RECURSIVE=y
CONFIG_USER_BUSYBOX_LS_FOLLOWLINKS=y
CONFIG_USER_BUSYBOX_LSMOD=y
# CONFIG_USER_BUSYBOX_MAKEDEVS is not set
# CONFIG_USER_BUSYBOX_MD5SUM is not set
CONFIG_USER_BUSYBOX_MKDIR=y
# CONFIG_USER_BUSYBOX_MKFS_MINIX is not set
CONFIG_USER_BUSYBOX_MKNOD=y
CONFIG_USER_BUSYBOX_MKTEMP=y
CONFIG_USER_BUSYBOX_MODPROBE=y
CONFIG_USER_BUSYBOX_MORE=y
CONFIG_USER_BUSYBOX_MOUNT=y
# CONFIG_USER_BUSYBOX_MOUNT_LOOP is not set
# CONFIG_USER_BUSYBOX_MTAB_SUPPORT is not set
CONFIG_USER_BUSYBOX_NFSMOUNT=y
CONFIG_USER_BUSYBOX_MV=y
CONFIG_USER_BUSYBOX_NC=y
CONFIG_USER_BUSYBOX_NSLOOKUP=y
# CONFIG_USER_BUSYBOX_PIDOF is not set
# CONFIG_USER_BUSYBOX_PING is not set
# CONFIG_USER_BUSYBOX_PIVOT_ROOT is not set
# CONFIG_USER_BUSYBOX_POWEROFF is not set
CONFIG_USER_BUSYBOX_PRINTF=y
CONFIG_USER_BUSYBOX_PS=y
CONFIG_USER_BUSYBOX_PWD=y
CONFIG_USER_BUSYBOX_RDATE=y
# CONFIG_USER_BUSYBOX_READLINK is not set
CONFIG_USER_BUSYBOX_REBOOT=y
CONFIG_USER_BUSYBOX_RENICE=y
CONFIG_USER_BUSYBOX_RESET=y
CONFIG_USER_BUSYBOX_RM=y
CONFIG_USER_BUSYBOX_RMDIR=y
CONFIG_USER_BUSYBOX_RMMOD=y
CONFIG_USER_BUSYBOX_ROUTE=y
# CONFIG_USER_BUSYBOX_RPM2CPIO is not set
# CONFIG_USER_BUSYBOX_SED is not set
# CONFIG_USER_BUSYBOX_SHELL is not set
CONFIG_USER_BUSYBOX_SLEEP=y
CONFIG_USER_BUSYBOX_SORT=y
CONFIG_USER_BUSYBOX_SORT_REVERSE=y
# CONFIG_USER_BUSYBOX_SORT_UNIQUE is not set
CONFIG_USER_BUSYBOX_STTY=y
CONFIG_USER_BUSYBOX_SYNC=y
CONFIG_USER_BUSYBOX_SYSLOGD=y
CONFIG_USER_BUSYBOX_REMOTE_LOG=y
# CONFIG_USER_BUSYBOX_IPC_SYSLOG is not set
CONFIG_USER_BUSYBOX_TAIL=y
# CONFIG_USER_BUSYBOX_FANCY_TAIL is not set
# CONFIG_USER_BUSYBOX_TAR is not set
CONFIG_USER_BUSYBOX_TEE=y
# CONFIG_USER_BUSYBOX_TELNET is not set
CONFIG_USER_BUSYBOX_TEST=y
CONFIG_USER_BUSYBOX_TFTP=y
CONFIG_USER_BUSYBOX_TFTP_PUT=y
CONFIG_USER_BUSYBOX_TFTP_GET=y
CONFIG_USER_BUSYBOX_TOUCH=y
CONFIG_USER_BUSYBOX_TR=y
# CONFIG_USER_BUSYBOX_TRACEROUTE is not set
CONFIG_USER_BUSYBOX_TRUE_FALSE=y
CONFIG_USER_BUSYBOX_TTY=y
CONFIG_USER_BUSYBOX_UMOUNT=y
CONFIG_USER_BUSYBOX_MOUNT_FORCE=y
CONFIG_USER_BUSYBOX_UNAME=y
CONFIG_USER_BUSYBOX_UNIQ=y
# CONFIG_USER_BUSYBOX_UNIX2DOS is not set
CONFIG_USER_BUSYBOX_UPTIME=y
CONFIG_USER_BUSYBOX_USLEEP=y
# CONFIG_USER_BUSYBOX_UUDECODE is not set
# CONFIG_USER_BUSYBOX_UUENCODE is not set
CONFIG_USER_BUSYBOX_VI=y
CONFIG_USER_BUSYBOX_VI_COLON=y
CONFIG_USER_BUSYBOX_VI_YANKMARK=y
CONFIG_USER_BUSYBOX_VI_SEARCH=y
CONFIG_USER_BUSYBOX_VI_USE_SIGNALS=y
CONFIG_USER_BUSYBOX_VI_DOT_CMD=y
CONFIG_USER_BUSYBOX_VI_READONLY=y
CONFIG_USER_BUSYBOX_VI_SETOPTS=y
CONFIG_USER_BUSYBOX_VI_SET=y
CONFIG_USER_BUSYBOX_VI_WIN_RESIZE=y
# CONFIG_USER_BUSYBOX_WATCHDOGD is not set
CONFIG_USER_BUSYBOX_WC=y
CONFIG_USER_BUSYBOX_WGET=y
CONFIG_USER_BUSYBOX_WGET_STATUSBAR=y
# CONFIG_USER_BUSYBOX_WGET_AUTHENTICATION is not set
CONFIG_USER_BUSYBOX_WHICH=y
CONFIG_USER_BUSYBOX_WHOAMI=y
CONFIG_USER_BUSYBOX_XARGS=y
CONFIG_USER_BUSYBOX_YES=y

#
# other features
#
# CONFIG_USER_BUSYBOX_VERBOSE_USAGE is not set
CONFIG_USER_BUSYBOX_AUTOWIDTH=y
# CONFIG_USER_BUSYBOX_2_2_MODULES is not set
CONFIG_USER_BUSYBOX_2_4_MODULES=y
# CONFIG_USER_BUSYBOX_2_6_MODULES is not set
# CONFIG_USER_BUSYBOX_INSMOD_VERSION_CHECKING is not set
CONFIG_USER_BUSYBOX_HUMAN_READABLE=y

#
# Tinylogin
#
CONFIG_USER_TINYLOGIN_TINYLOGIN=y

#
# Applets
#
CONFIG_USER_TINYLOGIN_ADDUSER=y
CONFIG_USER_TINYLOGIN_ADDGROUP=y
CONFIG_USER_TINYLOGIN_DELUSER=y
CONFIG_USER_TINYLOGIN_DELGROUP=y
CONFIG_USER_TINYLOGIN_LOGIN=y
# CONFIG_USER_TINYLOGIN_SECURETTY is not set
CONFIG_USER_TINYLOGIN_SU=y
# CONFIG_USER_TINYLOGIN_SULOGIN is not set
CONFIG_USER_TINYLOGIN_PASSWD=y
CONFIG_USER_TINYLOGIN_GETTY=y

#
# Features
#
CONFIG_USER_TINYLOGIN_SHADOWPASSWDS=y
# CONFIG_USER_TINYLOGIN_MD5_PASSWORDS is not set
# CONFIG_USER_TINYLOGIN_SHA1_PASSWORDS is not set
# CONFIG_USER_TINYLOGIN_TRIVIAL_HELP is not set

#
# MicroWindows
#
# CONFIG_USER_MICROWIN is not set

#
# Games
#
# CONFIG_USER_GAMES_ADVENT4 is not set
# CONFIG_USER_GAMES_DUNGEON is not set
# CONFIG_USER_GAMES_XMAME is not set

#
# Miscellaneous Configuration
#
# CONFIG_USER_RAMIMAGE_NONE is not set
# CONFIG_USER_RAMIMAGE_RAMFS64 is not set
CONFIG_USER_RAMIMAGE_RAMFS128=y
# CONFIG_USER_RAMIMAGE_RAMFS256 is not set
# CONFIG_USER_CGI_GENERIC is not set
# CONFIG_USER_CGI is not set
CONFIG_USER_FIREWALL_TOOLS=y

#
# Debug Builds
#
# CONFIG_LIB_DEBUG is not set
# CONFIG_USER_DEBUG is not set

#
# Debug tools
#
# CONFIG_USER_PROTECT is not set
# CONFIG_USER_TIMEPEG_TPT is not set
