.TH IPREDIR 8 "28 October 1999"
.SH NAME
ipredir -- NETtel IP Redirection
.SH SYNOPSIS
.PP
.B ipredir
.RB [ -l
.IR ipaddr_listen ]
.RB [ -o ]
.RB [ -v ]
.RB [ -h ]
.RB [ -f
.IR ipaddr_from ]
.RB [ -s
.IR ipaddr_to ]
.PP
.B ipredir
.RB [ --listen
.IR ipaddr_listen ]
.RB [ --out_junk ]
.RB [ --version ]
.RB [ --help ]
.RB [ --from
.IR ipaddr_from ]
.RB [ --send
.IR ipaddr_send ]
.SH DESCRIPTION
.B ipredir
is used to redirect any packet that has been sent to the
machine to a new machine. ipredirect can only listen to one port at a time
and it is therefore recommended that you set the port to somthing useful
using the -l option.
.SH OPTIONS
.TP
\fB-l\fR|\fB--listen \fIipaddr_listen
This is used to listen to a particular port using one of your addresses.
The address of 0 will indicate that any of your address can be used.
The port of 0 will listen to port 0 (which is useless so choose a better
number)

.TP
.BR -o | --out_junk
sends out junk packets to the address specifies by the -s option from the
address specified by the -f option as fast as it can.  Disregards the -l
option.
.TP
.BR -v | --version
displays the version information
.TP
.BR -h | --help
displays some simple help.
.TP
\fB-f\fR|\fB--from \fIipaddr_from
This is used to send from a particular addresses and port
The address of 0 will indicate that any of your address can be used.
The port of 0 will send using a kernel chosen port

.TP
\fB-s\fR|\fB--send \fIipaddr_send
This is used to send to a particular addresses and port.
The address of 0 is useless (choose a decent address - even broardcast
numbers like 192.168.0.255)
The port of 0 will send to port 0

.SH EXAMPLES
.PP
.B listen
on your address 192.168.0.111 port 55
and send from your address 203.24.151.66 port 23
to the computer 203.24.151.121 port 55

.PP
.B "ipredirect -l 192.168.0.111:55 -f 203.24.151.66:23 -s 203.24.151.121:55"
.SH AUTHORS
PoPToP is written by Chris Trew <ctrew@lineo.com>
.SH COPYRIGHT
Copyright \(co 1999 Chris Trew.
.LP
ipredir is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2, or (at your option) any later
version.
.LP
ipredir is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.
.LP
You should have received a copy of the GNU General Public License along
with PoPToP; see the file COPYING.  If not, write to the Free Software
Foundation, 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.SH AVAILABILITY
The most recent version of ipredir is available for download from
Lineo at
.IR http://www.uClinux.org/ .
.SH "SEE ALSO"
.BR ipfwadm (8),
