.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH UPNPD 8 "March  5, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
upnpd \- Linux UPnP Internet Gateway Device daemon.
.SH SYNOPSIS
.B upnpd
.RI <ext_ifname>
.RI <int_ifname>
.SH DESCRIPTION
This manual page documents briefly the
.B upnpd
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBupnpd\fP is a daemon that daemon that emulates Microsoft's Internet Connection Service (ICS). It implements the UPnP Internet Gateway Device specification (IGD) and allows UPnP aware clients, such as MSN Messenger to work properly from behind a NAT firewall.
.SH OPTIONS
A summary of options is included below.
.TP
.B ext_ifname
External interface name.
.TP
.B int_ifname
Internal interface name.
.SH AUTHOR
upnpd was written by Glover George and others.
.PP
This manual page was written by Jos\['e] Fonseca <j_r_fonseca@yahoo.co.uk>,
for the Debian project (but may be used by others).
