# $Id: Makefile,v 1.1 2004/11/01 16:48:44 ramona Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=avpops.so
LIBS= 

include ../../Makefile.modules
