#!/bin/sh
ln -s /dev/pty/m0 /dev/ptyp0
ln -s /dev/pty/m1 /dev/ptyp1
ln -s /dev/pty/m2 /dev/ptyp2
ln -s /dev/pty/m3 /dev/ptyp3
ln -s /dev/pty/m4 /dev/ptyp4
ln -s /dev/pty/m5 /dev/ptyp5
ln -s /dev/pty/m6 /dev/ptyp6
ln -s /dev/pty/m7 /dev/ptyp7
ln -s /dev/pty/m8 /dev/ptyp8
ln -s /dev/pty/m9 /dev/ptyp9
ln -s /dev/pty/m10 /dev/ptypa
ln -s /dev/pty/m11 /dev/ptypb
ln -s /dev/pty/m12 /dev/ptypc
ln -s /dev/pty/m13 /dev/ptypd
ln -s /dev/pty/m14 /dev/ptype
ln -s /dev/pty/m15 /dev/ptypf

ln -s /dev/pty/s0 /dev/ttyp0
ln -s /dev/pty/s1 /dev/ttyp1
ln -s /dev/pty/s2 /dev/ttyp2
ln -s /dev/pty/s3 /dev/ttyp3
ln -s /dev/pty/s4 /dev/ttyp4
ln -s /dev/pty/s5 /dev/ttyp5
ln -s /dev/pty/s6 /dev/ttyp6
ln -s /dev/pty/s7 /dev/ttyp7
ln -s /dev/pty/s8 /dev/ttyp8
ln -s /dev/pty/s9 /dev/ttyp9
ln -s /dev/pty/s10 /dev/ttypa
ln -s /dev/pty/s11 /dev/ttypb
ln -s /dev/pty/s12 /dev/ttypc
ln -s /dev/pty/s13 /dev/ttypd
ln -s /dev/pty/s14 /dev/ttype
ln -s /dev/pty/s15 /dev/ttypf

ln -s /dev/tts/0 /dev/ttyS0
ln -s /dev/tts/1 /dev/ttyS1

ln -s /dev/misc/clock /dev/clock
ln -s /dev/misc/dsp /dev/dsp
ln -s /dev/misc/led /dev/led
ln -s /dev/misc/scratchpad /dev/scratchpad
ln -s /dev/misc/watchdog /dev/watchdog
ln -s /dev/misc/timer1 /dev/timer1


