#include "db_config.h"
#ifdef HAVE_RPC
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../rpc_server/db_server.h"

bool_t
xdr___env_cachesize_msg (XDR *xdrs, __env_cachesize_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->gbytes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->bytes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->ncache))
				 return FALSE;
		} else {
			IXDR_PUT_U_LONG(buf, objp->dbenvcl_id);
			IXDR_PUT_U_LONG(buf, objp->gbytes);
			IXDR_PUT_U_LONG(buf, objp->bytes);
			IXDR_PUT_U_LONG(buf, objp->ncache);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->gbytes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->bytes))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->ncache))
				 return FALSE;
		} else {
			objp->dbenvcl_id = IXDR_GET_U_LONG(buf);
			objp->gbytes = IXDR_GET_U_LONG(buf);
			objp->bytes = IXDR_GET_U_LONG(buf);
			objp->ncache = IXDR_GET_U_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->gbytes))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->bytes))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->ncache))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_cachesize_reply (XDR *xdrs, __env_cachesize_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_close_msg (XDR *xdrs, __env_close_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_close_reply (XDR *xdrs, __env_close_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_create_msg (XDR *xdrs, __env_create_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->timeout))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_create_reply (XDR *xdrs, __env_create_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->envcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_flags_msg (XDR *xdrs, __env_flags_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->onoff))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_flags_reply (XDR *xdrs, __env_flags_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_open_msg (XDR *xdrs, __env_open_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->home, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_open_reply (XDR *xdrs, __env_open_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_remove_msg (XDR *xdrs, __env_remove_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbenvcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->home, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___env_remove_reply (XDR *xdrs, __env_remove_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_abort_msg (XDR *xdrs, __txn_abort_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_abort_reply (XDR *xdrs, __txn_abort_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_begin_msg (XDR *xdrs, __txn_begin_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->envpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->parentcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_begin_reply (XDR *xdrs, __txn_begin_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnidcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_commit_msg (XDR *xdrs, __txn_commit_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___txn_commit_reply (XDR *xdrs, __txn_commit_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_bt_maxkey_msg (XDR *xdrs, __db_bt_maxkey_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->maxkey))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_bt_maxkey_reply (XDR *xdrs, __db_bt_maxkey_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_bt_minkey_msg (XDR *xdrs, __db_bt_minkey_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->minkey))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_bt_minkey_reply (XDR *xdrs, __db_bt_minkey_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_close_msg (XDR *xdrs, __db_close_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_close_reply (XDR *xdrs, __db_close_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_create_msg (XDR *xdrs, __db_create_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->envpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_create_reply (XDR *xdrs, __db_create_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_del_msg (XDR *xdrs, __db_del_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbpcl_id);
		IXDR_PUT_U_LONG(buf, objp->txnpcl_id);
		IXDR_PUT_U_LONG(buf, objp->keydlen);
		IXDR_PUT_U_LONG(buf, objp->keydoff);
		IXDR_PUT_U_LONG(buf, objp->keyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		objp->dbpcl_id = IXDR_GET_U_LONG(buf);
		objp->txnpcl_id = IXDR_GET_U_LONG(buf);
		objp->keydlen = IXDR_GET_U_LONG(buf);
		objp->keydoff = IXDR_GET_U_LONG(buf);
		objp->keyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_del_reply (XDR *xdrs, __db_del_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_extentsize_msg (XDR *xdrs, __db_extentsize_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->extentsize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_extentsize_reply (XDR *xdrs, __db_extentsize_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_flags_msg (XDR *xdrs, __db_flags_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_flags_reply (XDR *xdrs, __db_flags_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_msg (XDR *xdrs, __db_get_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbpcl_id);
		IXDR_PUT_U_LONG(buf, objp->txnpcl_id);
		IXDR_PUT_U_LONG(buf, objp->keydlen);
		IXDR_PUT_U_LONG(buf, objp->keydoff);
		IXDR_PUT_U_LONG(buf, objp->keyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->datadlen);
		IXDR_PUT_U_LONG(buf, objp->datadoff);
		IXDR_PUT_U_LONG(buf, objp->dataflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		objp->dbpcl_id = IXDR_GET_U_LONG(buf);
		objp->txnpcl_id = IXDR_GET_U_LONG(buf);
		objp->keydlen = IXDR_GET_U_LONG(buf);
		objp->keydoff = IXDR_GET_U_LONG(buf);
		objp->keyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		objp->datadlen = IXDR_GET_U_LONG(buf);
		objp->datadoff = IXDR_GET_U_LONG(buf);
		objp->dataflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_get_reply (XDR *xdrs, __db_get_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_h_ffactor_msg (XDR *xdrs, __db_h_ffactor_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->ffactor))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_h_ffactor_reply (XDR *xdrs, __db_h_ffactor_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_h_nelem_msg (XDR *xdrs, __db_h_nelem_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->nelem))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_h_nelem_reply (XDR *xdrs, __db_h_nelem_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_key_range_msg (XDR *xdrs, __db_key_range_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbpcl_id);
		IXDR_PUT_U_LONG(buf, objp->txnpcl_id);
		IXDR_PUT_U_LONG(buf, objp->keydlen);
		IXDR_PUT_U_LONG(buf, objp->keydoff);
		IXDR_PUT_U_LONG(buf, objp->keyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		objp->dbpcl_id = IXDR_GET_U_LONG(buf);
		objp->txnpcl_id = IXDR_GET_U_LONG(buf);
		objp->keydlen = IXDR_GET_U_LONG(buf);
		objp->keydoff = IXDR_GET_U_LONG(buf);
		objp->keyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_key_range_reply (XDR *xdrs, __db_key_range_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->less))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->equal))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->greater))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_lorder_msg (XDR *xdrs, __db_lorder_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->lorder))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_lorder_reply (XDR *xdrs, __db_lorder_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_open_msg (XDR *xdrs, __db_open_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->subdb, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->mode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_open_reply (XDR *xdrs, __db_open_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dbflags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_pagesize_msg (XDR *xdrs, __db_pagesize_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pagesize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_pagesize_reply (XDR *xdrs, __db_pagesize_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_put_msg (XDR *xdrs, __db_put_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbpcl_id);
		IXDR_PUT_U_LONG(buf, objp->txnpcl_id);
		IXDR_PUT_U_LONG(buf, objp->keydlen);
		IXDR_PUT_U_LONG(buf, objp->keydoff);
		IXDR_PUT_U_LONG(buf, objp->keyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->datadlen);
		IXDR_PUT_U_LONG(buf, objp->datadoff);
		IXDR_PUT_U_LONG(buf, objp->dataflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		objp->dbpcl_id = IXDR_GET_U_LONG(buf);
		objp->txnpcl_id = IXDR_GET_U_LONG(buf);
		objp->keydlen = IXDR_GET_U_LONG(buf);
		objp->keydoff = IXDR_GET_U_LONG(buf);
		objp->keyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		objp->datadlen = IXDR_GET_U_LONG(buf);
		objp->datadoff = IXDR_GET_U_LONG(buf);
		objp->dataflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_put_reply (XDR *xdrs, __db_put_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_re_delim_msg (XDR *xdrs, __db_re_delim_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->delim))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_re_delim_reply (XDR *xdrs, __db_re_delim_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_re_len_msg (XDR *xdrs, __db_re_len_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->len))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_re_len_reply (XDR *xdrs, __db_re_len_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_re_pad_msg (XDR *xdrs, __db_re_pad_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->pad))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_re_pad_reply (XDR *xdrs, __db_re_pad_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_remove_msg (XDR *xdrs, __db_remove_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->subdb, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_remove_reply (XDR *xdrs, __db_remove_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_rename_msg (XDR *xdrs, __db_rename_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->subdb, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->newname, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_rename_reply (XDR *xdrs, __db_rename_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_stat_msg (XDR *xdrs, __db_stat_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_stat_statsreplist (XDR *xdrs, __db_stat_statsreplist *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->ent.ent_val, (u_int *) &objp->ent.ent_len, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (__db_stat_statsreplist), (xdrproc_t) xdr___db_stat_statsreplist))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_stat_reply (XDR *xdrs, __db_stat_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->statslist, sizeof (__db_stat_statsreplist), (xdrproc_t) xdr___db_stat_statsreplist))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_swapped_msg (XDR *xdrs, __db_swapped_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_swapped_reply (XDR *xdrs, __db_swapped_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_sync_msg (XDR *xdrs, __db_sync_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_sync_reply (XDR *xdrs, __db_sync_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_cursor_msg (XDR *xdrs, __db_cursor_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->txnpcl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_cursor_reply (XDR *xdrs, __db_cursor_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dbcidcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_join_curslist (XDR *xdrs, __db_join_curslist *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->ent.ent_val, (u_int *) &objp->ent.ent_len, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (__db_join_curslist), (xdrproc_t) xdr___db_join_curslist))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_join_msg (XDR *xdrs, __db_join_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbpcl_id))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->curslist, sizeof (__db_join_curslist), (xdrproc_t) xdr___db_join_curslist))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___db_join_reply (XDR *xdrs, __db_join_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dbcidcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_close_msg (XDR *xdrs, __dbc_close_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_close_reply (XDR *xdrs, __dbc_close_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_count_msg (XDR *xdrs, __dbc_count_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_count_reply (XDR *xdrs, __dbc_count_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dupcount))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_del_msg (XDR *xdrs, __dbc_del_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_del_reply (XDR *xdrs, __dbc_del_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_dup_msg (XDR *xdrs, __dbc_dup_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_dup_reply (XDR *xdrs, __dbc_dup_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dbcidcl_id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_get_msg (XDR *xdrs, __dbc_get_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbccl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbccl_id);
		IXDR_PUT_U_LONG(buf, objp->keydlen);
		IXDR_PUT_U_LONG(buf, objp->keydoff);
		IXDR_PUT_U_LONG(buf, objp->keyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->datadlen);
		IXDR_PUT_U_LONG(buf, objp->datadoff);
		IXDR_PUT_U_LONG(buf, objp->dataflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbccl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		objp->dbccl_id = IXDR_GET_U_LONG(buf);
		objp->keydlen = IXDR_GET_U_LONG(buf);
		objp->keydoff = IXDR_GET_U_LONG(buf);
		objp->keyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		objp->datadlen = IXDR_GET_U_LONG(buf);
		objp->datadoff = IXDR_GET_U_LONG(buf);
		objp->dataflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_get_reply (XDR *xdrs, __dbc_get_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_put_msg (XDR *xdrs, __dbc_put_msg *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbccl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->dbccl_id);
		IXDR_PUT_U_LONG(buf, objp->keydlen);
		IXDR_PUT_U_LONG(buf, objp->keydoff);
		IXDR_PUT_U_LONG(buf, objp->keyflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->datadlen);
		IXDR_PUT_U_LONG(buf, objp->datadoff);
		IXDR_PUT_U_LONG(buf, objp->dataflags);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->dbccl_id))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keydoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->keyflags))
				 return FALSE;

		} else {
		objp->dbccl_id = IXDR_GET_U_LONG(buf);
		objp->keydlen = IXDR_GET_U_LONG(buf);
		objp->keydoff = IXDR_GET_U_LONG(buf);
		objp->keyflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->datadlen))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->datadoff))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->dataflags))
				 return FALSE;

		} else {
		objp->datadlen = IXDR_GET_U_LONG(buf);
		objp->datadoff = IXDR_GET_U_LONG(buf);
		objp->dataflags = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
			 return FALSE;
		 if (!xdr_u_int (xdrs, &objp->flags))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->dbccl_id))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keydoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->keyflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadlen))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->datadoff))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->dataflags))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->datadata.datadata_val, (u_int *) &objp->datadata.datadata_len, ~0))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr___dbc_put_reply (XDR *xdrs, __dbc_put_reply *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->keydata.keydata_val, (u_int *) &objp->keydata.keydata_len, ~0))
		 return FALSE;
	return TRUE;
}
#endif /* HAVE_RPC */
