#!/bin/sh
logger -p local1.info $0 $* 

. /etc/diald/config

# Setup the Link
/sbin/isdnctrl addphone $1 out $PHONE
/sbin/isdnctrl dial $1

# Setup Routes
# /sbin/route add janus $1 
/sbin/route add default $1
/sbin/route add $4 $1

exit 0
