#!/bin/sh
logger -p local1.info $0 $* 

. /etc/diald/config

# Setup Routes to Snoop Interface
/sbin/route add default $1
/sbin/route add $4 $1

# Hangup the Line
/sbin/isdnctrl delphone $1 out $PHONE
/sbin/isdnctrl delphone $1 out $PHONE
/sbin/isdnctrl delphone $1 out $PHONE
/sbin/isdnctrl hangup $1

exit 0
