# uClibc stat tests
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.

include ../Test.mak

CFLAGS_stat64 := -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64

DODIFF_stat   := 1
DODIFF_stat64 := 1

OPTS_stat   := Makefile
OPTS_stat64 := Makefile
