.\" -*- nroff -*-
.\" Copyright 1996-2001 Hans Reiser.
.\" 
.TH MKREISERFS 8 "March 2001" "Reiserfsprogs-3.x.0j"
.SH NAME
mkreiserfs \- create a Linux Reiserfs file system
.SH SYNOPSIS
.B mkreiserfs
[
.B -h
.I r5 
| 
.I tea
|
.I rupasov
] [
.B \-v
.I 1 
|
.I 2
] [
.B -q
]
.I device
[
.I size-in-blocks
]
.SH DESCRIPTION
It creates a Linux Reiserfs file system on a device
(usually a disk partition).
.TP
.I device
is the special file corresponding to the device (e.g /dev/hdXX for
IDE disk partition or /dev/sdXX for SCSI disk partition).
.TP
.I block-count
is the number of blocks on the device. If omitted, it will be
determined by
.B mkreiserfs
automatically.
.SH OPTIONS
.TP
\fB\-h \fIr5\fR |\fI tea\fR |\fI rupasov
This specifies the name of hash function file names in directories
will be sorted with. Choose one of the above. 'r5' is default.
.TP
\fB\-v \fI1\fR |\fI 2
This specifies format new filsystem has to be of.
.TP
\fB\-q\fR
This makes the progress bar much less verbose.  Useful when
logged in via a slow link (e.g. serial console).
.SH AUTHOR
This version of
.B mkreiserfs
has been written by Hans Reiser <reiser@idiom.com>.
.SH BUGS
No other blocksizes but 4k are available.
Please, report about other bugs to Hans Reiser <reiser@idiom.com>.
.SH SEE ALSO
.BR reiserfsck (8),
.BR debugreiserfs (8)
