#!/bin/sh

# Dummy mysql_config executable. Prints out the linker options required to 
# link with our MySQL build. Equivalent to running 'mysql_config --libs'

echo "-L$ROOTDIR/user/mysql/libmysql/.libs -lmysqlclient -lz -lm"
