HOSTCC   = cc
HOSTCXX  = c++

SMAKE = CC=$(HOSTCC) CXX=$(HOSTCXX) $(MAKE)

.PHONY: conf
conf: $(SCRIPTSDIR)/conf

$(SCRIPTSDIR)/conf:
	$(SMAKE) -C $(SCRIPTSDIR) conf

.PHONY: mconf
mconf: $(SCRIPTSDIR)/mconf

$(SCRIPTSDIR)/mconf:
	$(SMAKE) -C $(SCRIPTSDIR) mconf

.PHONY: gconf
gconf: $(SCRIPTSDIR)/gconf

$(SCRIPTSDIR)/gconf:
	$(SMAKE) -C $(SCRIPTSDIR) gconf

.PHONY: qconf
qconf: $(SCRIPTSDIR)/qconf

$(SCRIPTSDIR)/qconf:
	$(SMAKE) -C $(SCRIPTSDIR) qconf

.PHONY: confclean
confclean:
	$(MAKE) -C $(SCRIPTSDIR) clean
