EXEC1 = dhcpd
OBJS1 = dhcpd.o arpping.o

EXEC2 = tools/makeiplist
OBJS2 = tools/makeiplist.o

EXEC3 = tools/browseiplist
OBJS3 = tools/browseiplist.o


all: $(EXEC1) $(EXEC2) $(EXEC3)


$(EXEC1): $(OBJS1)
	gcc $(OBJS1) -o $(EXEC1)

$(EXEC2): $(OBJS2)
	gcc $(OBJS2) -o $(EXEC2)

$(EXEC3): $(OBJS3)
	gcc $(OBJS3) -o $(EXEC3)

clean:
	-rm -f $(EXEC1) $(EXEC2) $(EXEC3) *.elf *.o core

$(OBJS1): dhcpd.h arpping.h

$(OBJS2): 

$(OBJS3): 

