SRCS=\
 ../../Common/InBuffer.cpp \
 ../../Common/StreamUtils.cpp \
 ../../Common/OutBuffer.cpp \
 ./DllExports.cpp \
 ../LZ/LZOutWindow.cpp \
 Original/crc.cpp \
 Original/errhnd.cpp \
 Original/getbits.cpp \
 Original/rarvm.cpp \
 Original/rdwrfn.cpp \
 Original/resource.cpp \
 Original/smallfn.cpp \
 Original/system.cpp \
 Original/unpack.cpp \
 ../Rar20/Rar20Decoder.cpp \
 ../Rar20/Rar20Multimedia.cpp \
 ./Rar29Decoder.cpp

DllExports.o : ./DllExports.cpp
	$(CXX) $(CFLAGS) ./DllExports.cpp
InBuffer.o : ../../Common/InBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InBuffer.cpp
crc.o : Original/crc.cpp
	$(CXX) $(CFLAGS) Original/crc.cpp
errhnd.o : Original/errhnd.cpp
	$(CXX) $(CFLAGS) Original/errhnd.cpp
getbits.o : Original/getbits.cpp
	$(CXX) $(CFLAGS) Original/getbits.cpp
rarvm.o : Original/rarvm.cpp
	$(CXX) $(CFLAGS) Original/rarvm.cpp
rdwrfn.o : Original/rdwrfn.cpp
	$(CXX) $(CFLAGS) Original/rdwrfn.cpp
resource.o : Original/resource.cpp
	$(CXX) $(CFLAGS) Original/resource.cpp
smallfn.o : Original/smallfn.cpp
	$(CXX) $(CFLAGS) Original/smallfn.cpp
system.o : Original/system.cpp
	$(CXX) $(CFLAGS) Original/system.cpp
unpack.o : Original/unpack.cpp
	$(CXX) $(CFLAGS) Original/unpack.cpp
Rar20Decoder.o : ../Rar20/Rar20Decoder.cpp
	$(CXX) $(CFLAGS) ../Rar20/Rar20Decoder.cpp
Rar20Multimedia.o : ../Rar20/Rar20Multimedia.cpp
	$(CXX) $(CFLAGS) ../Rar20/Rar20Multimedia.cpp
LZOutWindow.o : ../LZ/LZOutWindow.cpp
	$(CXX) $(CFLAGS) ../LZ/LZOutWindow.cpp
Rar29Decoder.o : ./Rar29Decoder.cpp
	$(CXX) $(CFLAGS) ./Rar29Decoder.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
OutBuffer.o : ../../Common/OutBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/OutBuffer.cpp
