#!/bin/sh
#
#	mkconfig -- convert from uClinux/dist config to local .config
#
#	Although the dist config sources the local config files it
#	uses the fully qualified package/applet names. So we need to
#	convert these now to the original local busybox small names.
#

grep CONFIG_USER_BUSYBOX_ ../../config/.config | \
	grep -v CONFIG_USER_BUSYBOX_BUSYBOX=y | \
	sed -e 's/CONFIG_USER_BUSYBOX_/CONFIG_/'

exit 0
