.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KDUMP 8 "Jul 27, 2005"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
kdump \- This is just a placeholder until real man page has been written
.SH SYNOPSIS
.B kdump
.RI [ options ] " start_address" ...
.SH DESCRIPTION
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBkdump\fP does not have a man page yet.
.SH OPTIONS
.\"These programs follow the usual GNU command line syntax, with long
.\"options starting with two dashes (`-').
.\"A summary of options is included below.
.\"For a complete description, see the Info files.
.SH SEE ALSO
.SH AUTHOR
kdump was written by Eric Biederman.
.PP
This manual page was written by Khalid Aziz <khalid.aziz@hp.com>,
for the Debian project (but may be used by others).
