.Dd May 26, 2001
.Dt FLASHW 8
.Os "uClinux-coldfire-tools"
.Sh NAME
.Nm flashw
.Nd write either character data or binary data to individual flash devices.
.Sh SYNOPSIS
.Nm flashw
.Op Fl hvbe?
.Op Fl f Ar file | data
.Ar rom-device
.Sh DESCRIPTION
Allows writing data to any of the flash devices on the system
(labelled /dev/romx on coldfire based systems).
.Sh OPERATION
.Pp
When invoked,
.Nm flashw
allows either ascii, or binary data to be written out to a flash device.  The 
previous contents are over-written, and the space not filled with data is
rendered blank (0xFF for most flash devices).
.Sh COMMAND LINE
.Bl -tag -width Ds
.It Fl v 
Output version information for 
.Nm flashw.
.It Fl h, ?
Output usage information.
.It Fl b
Assume
.Ar data 
is a comma seperated list of binary data, or in the case of the
.Fl f
option, 
.Ar file
contains a comma seperated list of binary data.
.It Fl f Ar file
Use
.Ar file
as the source of the data.  It may contain ascii data, or if the 
.Fl b
option is used, binary data.
.It Ar data
The data that will be programmed into
.Ar rom-device.
This data can be either in ascii or binary form (depending on whether the
.Fl b
flag is set).
.It Ar rom-device
The rom device to put the data into.
.Sh SEE ALSO
.Xr netflash 8
.Sh AUTHOR
Greg Ungerer (gerg@lineo.com)
