.if n .ds Q \&"
.if t .ds Q ``
.if n .ds U \&"
.if t .ds U ''
.TH "frox" 8 
.tr \&
.nr bi 0
.nr ll 0
.nr el 0
.de DS
..
.de DE
..
.de Pp
.ie \\n(ll>0 \{\
.ie \\n(bi=1 \{\
.nr bi 0
.if \\n(t\\n(ll=0 \{.IP \\(bu\}
.if \\n(t\\n(ll=1 \{.IP \\n+(e\\n(el.\}
.\}
.el .sp 
.\}
.el \{\
.ie \\nh=1 \{\
.LP
.nr h 0
.\}
.el .PP 
.\}
..
.SH NAME

.Pp
frox - a transparent ftp proxy and cache.
.SH SYNOPSIS

.Pp
frox [-f file]
.Pp
frox -h
.SH DESCRIPTION

.Pp
Frox is a transparent ftp proxy. It also has support for
non-transparent connections, caching of anonymous ftp, and active
--> passive conversion of data connections. 
.SH OPTIONS

.Pp
-f file  Use file as the configuration file
.Pp
-h       Display help
.SH BUGS

.Pp
Funny things will probably happen if you attempt to do a 
restart on an anonymous file upload.
.Pp
IPV6 is not supported.
.SH SEE ALSO

.Pp
ftp(1), frox.conf(5), ftpd(8), RFC 959
.SH AUTHOR

.Pp
James Hollingshead <frox at hollo.org>
.Pp
Homepage http://frox.sourceforge.net