# Makefile for uClibc
#
# Copyright (C) 2000-2006 Erik Andersen <andersen@uclibc.org>
#
# Licensed under the LGPL v2.1, see the file COPYING.LIB in this tarball.
#

CSRC := brk.c bsdsetjmp.c clone.c syscall.c

SSRC := __longjmp.S setjmp.S bsd-_setjmp.S vfork.S

include $(top_srcdir)libc/sysdeps/linux/Makefile.commonarch
