# $Id: Makefile,v 1.1 2004/09/09 17:05:45 jiri Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=gflags.so
LIBS=

include ../../Makefile.modules

