# $Id: Makefile,v 1.8 1994/07/25 16:04:37 gkim Exp $
#
# Makefile for man pages

all:	install

install:
	cp siggen.8 $(MANDIR)/man8
	cp tripwire.8 $(MANDIR)/man8
	cp tw.config.5 $(MANDIR)/man5
	chmod 644 $(MANDIR)/man8/siggen.8
	chmod 644 $(MANDIR)/man8/tripwire.8
	chmod 644 $(MANDIR)/man5/tw.config.5

clean:

