.\" $Id: twconvert.8,v 1.4 1994/04/04 00:34:15 gkim Exp $
.\"
.TH TWCONVERT 8 "December 11, 1992"
.SH NAME
twconvert \- convert v1.0 Tripwire databases to v1.1
.SH SYNOPSIS
.B twconvert
.SH DESCRIPTION
.LP
\fItwconvert\fP is a utility that converts all the base-64 values in a
older database files (database formats 1 and 2)  to that used in v1.1
(database format 3).  \fItwconvert\fP reads in the database from
\fIstdin\fP and outputs the converted database to \fIstdout\fP.  No
arguments are used.
.LP
\fItwconvert\fP automatically detects which database format the input
database is using.
.LP
Because database version 4 contains more information than prior
versions, version 4 databases cannot be converted from older
versions.  Instead, they must be reinitialized by Tripwire.  (In this
regard, \fItwconvert\fP is vestigal, but will undoubtedly be used in
the future.)
.SH OPTIONS
None
.SH AUTHORS
.nf
Gene Kim
Purdue University
gkim@cs.purdue.edu
.fi


