.TH RDATE 1 "February 2000" "Utilities" "Red Hat"
.SH NAME
rdate \- get the time via the network
.SH "SYNOPSIS"
.B rdate
[\-p] [\-s] [host...]
.SH "DESCRIPTION"
.B rdate
connects to an RFC 868 time server over a TCP/IP network, printing the returned time and/or setting the system clock.
.fi
.SS OPTIONS
.TP
.I \-p
Print the time returned by the remote machine.
.TP
.I \-s
Set the system time to the returned time.
.SH HISTORY
.TP
2000-02-04 Elliot Lee <sopwith@redhat.com>
Wrote it (previous incarnation had license problems, all 200 lines of it).
