#! /bin/bash
# $Id: disttest,v 1.2 2003/12/04 20:14:40 ensc Exp $

# Copyright (C) 2003 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.


: ${srcdir=.}
: ${MAKE=make}

ok=1

tmpfile=$(mktemp /tmp/disttest.XXXXXX)
trap "rm -f $tmpfile" EXIT

while read line; do
    eval set -- $line
    #echo "Testing with '$@'"
    if ${MAKE} distcheck "$@" &>$tmpfile; then
	echo -n "PASS: "
    else
	cat $tmpfile
	echo -n "FAIL: "
	ok=
    fi >&2
    echo "./configure $@"
done < $srcdir/disttest-data

test "$ok"