.TH NASL-CONFIG 1 "November 1999" "Debian Project" "Nessus Attack Scripting Language"
.SH NAME
nasl-config \- displays compiler/linker flags for NASL library
.SH SYNOPSIS
.B nasl-config
.I <[--cflags] [--ldflags] [--libs]>
.SH DESCRIPTION
.BR nasl-config
script displays the compiler/linker flags other program sources
can use to link to the Nessus Attack Scripting Language library.
.SH OPTIONS
.TP
.B \-\-cflags
Show $(CFLAGS) variable.
.TP
.B \-\-libs
Show $(LIBS) variable.
.TP
.B \-\-version
Show the version of NASL.
.SH SEE ALSO
.BR nessus (1),
.BR nessusd (8).
.SH AUTHOR
NASL, along with the rest of Nessus, is made by Renaud Deraison
<deraison@cvs.nessus.org>.
.sp
This manual page was written by Josip Rodin <jrodin@jagor.srce.hr>.
