.TH WLANCTL-NG 8
.SH NAME
wlanctl-ng \- control utility for linux-wlan-ng 802.11 devices
.SH SYNOPSIS
.B wlanctl-ng interface|verson|commands|mibs cmd cmdarg [cmdarg..]
.SH DESCRIPTION
The wlanctl-ng utility program is used to set up linux-wlan-ng 802.11
devices. linux-wlan-ng devices are configured using a MIB.
.P
Only experts will want to use this program, as it is quite complicated.
Everyone else edits a config file and uses a script that runs this program
as necessary.
.SH OPTIONS
.TP
.B commands
Output a list of all available commands.
.TP
.B mibs
Outputs a list of available mibs.
.TP
.B version
Outputs the version of the program.
.TP
.B interface
The name of a wireless network interface, such as wlan0.
.SH AUTHOR
This minimal man page was written by Joey Hess.
