.TH WLAND 8
.SH NAME
wland \- linux-wlan-ng daemon
.SH SYNOPSIS
.B wland [-V|-v] [-d wlandpath] [-u]
.SH DESCRIPTION
.B wland
is a daemon for receiving and handling events from 802.11 services and
MAC-specific linux-wlan-ng drivers. It is not currently used.
.SH OPTIONS
.TP
.B -V
.TP
.B -v
Display version number.
.TP
.B -d wlandpath
Specify the directory to run in.
.TP 
.B -u
Do not daemonize; run in foreground.
.SH AUTHOR
This minimal man page was written by Joey Hess.
