#
#	Makefile -- Configuration Setup Makefile. 
#
#	Copyright (c) Mbedthis Software LLC, 2003-2004. All Rights Reserved.
#

include make.dep

cleanExtra:
	@rm -f config.args config.cache *.defaults 

## Local variables:
## tab-width: 4
## End:
## vim: tw=78 sw=4 ts=4
