#
# Automatically generated make config: don't edit
# Dist builder
#
CONFIG_MODULES=y

#
# Agere Wireless Card Modules
#
# CONFIG_MODULES_WLAGS49_H25_CS is not set

#
# Audio Modules
#
# CONFIG_MODULES_AUDIO_AD1845 is not set

#
# Crypto Modules
#
# CONFIG_MODULES_CRYPTO_HIFN7901 is not set
# CONFIG_MODULES_CRYPTO_HIFN7951 is not set
# CONFIG_MODULES_CRYPTO_SAFENET is not set
# CONFIG_MODULES_LZS_LZS is not set

#
# OCF Configuration
#
# CONFIG_OCF_OCF is not set

#
# LZS software compression
#

#
# Debug Modules
#
# CONFIG_MODULES_MCF_FULL_MEMORY_PROTECT is not set

#
# IO Modules
#
# CONFIG_MODULES_SGIO is not set

#
# XSCALE/IXP400 Modules
#
CONFIG_IXP400_LIB=y
# CONFIG_IXP400_LIB_1_3 is not set
# CONFIG_IXP400_LIB_1_4 is not set
# CONFIG_IXP400_LIB_2_0 is not set
CONFIG_IXP400_LIB_2_1=y
# CONFIG_IXP400_LIB_2_4 is not set
# CONFIG_IXP400_ETH_1_3 is not set
# CONFIG_IXP400_ETH_1_4 is not set
# CONFIG_IXP400_ETH_2_0 is not set
CONFIG_IXP400_ETH_2_1=y
# CONFIG_IXP400_ETH_2_4 is not set
CONFIG_IXP400_COMPONENTS=y
# CONFIG_IXP425_ATM is not set
CONFIG_IXP400_ETH=y
CONFIG_IXP425_IXP_AS_ETH=y
# CONFIG_IXP400_NAPI is not set
CONFIG_IXP400_ETH_ALL=y
# CONFIG_IXP400_ETH_NPEB_ONLY is not set
# CONFIG_IXP400_ETH_NPEC_ONLY is not set
# CONFIG_IXP400_ETH_SKB_RECYCLE is not set
# CONFIG_IXP400_ETH_QDISC_ENABLED is not set

#
# Components
#
# CONFIG_IXP425_COMPONENT_ADSL is not set
# CONFIG_IXP425_COMPONENT_ATMDACC is not set
# CONFIG_IXP425_COMPONENT_ATMM is not set
# CONFIG_IXP425_COMPONENT_ATMSCH is not set
CONFIG_IXP425_COMPONENT_QMGR=y
CONFIG_IXP425_COMPONENT_NPEMH=y
CONFIG_IXP425_COMPONENT_NPEDL=y
# CONFIG_IXP425_COMPONENT_CODEC is not set
CONFIG_IXP425_COMPONENT_ETHACC=y
# CONFIG_IXP425_COMPONENT_ETHDB is not set
CONFIG_IXP425_COMPONENT_ETHMII=y
# CONFIG_IXP425_COMPONENT_HSSACC is not set
# CONFIG_IXP425_COMPONENT_TIMERCTRL is not set
# CONFIG_IXP425_COMPONENT_USB is not set
# CONFIG_IXP425_COMPONENT_UARTACC is not set
CONFIG_IXP425_COMPONENT_OSSL=y
CONFIG_IXP425_COMPONENT_OSSERVICES=y
CONFIG_IXP425_COMPONENT_FEATURECTRL=y
# CONFIG_IXP425_COMPONENT_PERFPROFACC is not set
CONFIG_IXP425_COMPONENT_CRYPTOACC=y
# CONFIG_IXP425_COMPONENT_DMAACC is not set
# CONFIG_IXP425_COMPONENT_ETHMAC_RECOVERY is not set

#
# Codelets
#
# CONFIG_IXP425_CODELET_ETHAAL5APP is not set
# CONFIG_IXP425_CODELET_HSSACC is not set
# CONFIG_IXP425_CODELET_ETHACC is not set
# CONFIG_IXP425_CODELET_USB is not set
# CONFIG_IXP425_CODELET_TIMERS is not set
# CONFIG_IXP425_CODELET_PERFPROFACC is not set
# CONFIG_IXP425_CODELET_ATM is not set
# CONFIG_IXP425_CODELET_DSPENG is not set
# CONFIG_IXP425_CODELET_CRYPTOACC is not set
# CONFIG_IXP425_CODELET_DMAACC is not set

#
# LCD Modules
#
# CONFIG_MODULES_LCD_LCDTXT is not set

#
# KeyPad Modules
#
# CONFIG_MODULES_KEYPAD_KEYPAD is not set

#
# QTAB Modules
#
# CONFIG_MODULES_QTAB_FCC is not set
# CONFIG_MODULES_QTAB_MDIGI is not set
# CONFIG_MODULES_QTAB_SMARTREADER is not set

#
# Wireless Modules
#
# CONFIG_MODULES_RALINK is not set

#
# Satellite Modules
#
# CONFIG_MODULES_SAT_PENTANET is not set
# CONFIG_MODULES_SAT_PENTAVAL is not set

#
# VMWare Modules
#
# CONFIG_MODULES_VMWARE_VMXNET is not set
# CONFIG_MODULES_VMWARE_VMSYNC is not set
# CONFIG_MODULES_VMWARE_VMMEMCTL is not set
# CONFIG_MODULES_VMWARE_VMHGFS is not set
# CONFIG_MODULES_VMWARE_VMBLOCK is not set

#
# Lucent/Agere Modules
#
# CONFIG_MODULES_ET1310 is not set

#
# USB Modules
#
# CONFIG_MODULES_ADSL_SPEEDTOUCH is not set
# CONFIG_MODULES_SPCA5XX_WEBCAM is not set
# CONFIG_MODULES_OV51X_WEBCAM is not set
# CONFIG_MODULES_QC_USB_WEBCAM is not set
# CONFIG_MODULES_DM9601_ETH is not set
