# $Id: Makefile,v 1.1.10.1 2005/03/01 10:44:21 dcm Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=xlog.so
LIBS=

include ../../Makefile.modules
