
EXEC = bpalogin 
OBJS = bpalogin.o gen_md5.o protocol.o transaction.o getopt.o getopt1.o


all: $(EXEC)

$(EXEC): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $(OBJS) $(LDLIBS)

clean:
	-rm -f $(EXEC) *.elf *.o

$(OBJS): bpalogin.h our_getopt.h

