
EXEC = bpalogin
OBJS = bpalogin.o protocol.o transaction.o gen_md5.o
bpalogin: $(OBJS)
	gcc -o $(EXEC) -g $(OBJS) -lm -lbsd

clean:
	rm -f *.o $(EXEC)

$(OBJS): bpalogin.h

install:
	install -m 700 bpalogin /usr/local/sbin
	install -m 700 bpalogin.conf /etc
