
ROOTDIR = $(shell pwd)/../..
include $(ROOTDIR)/common.mk
include $(ROOTDIR)/user/arch/coldfire/build.mk
CONVERT  = $(ELF2FLT) $(FLTFLAGS) $(EXEC).elf -o $(EXEC)

all: $(EXEC)

$(EXEC): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $(OBJS) $(LDLIBS)

