# $Id: Makefile,v 1.2.2.3 2005/09/07 16:23:00 andrei Exp $
#
# avp_radius module Makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
include ../../Makefile.radius

auto_gen=
NAME=avp_radius.so



include ../../Makefile.modules
