.\" .IX pvf
.TH "autopvf" "1" "1.4" "autopvf" "PVF tools"
.SH "NAME"
\fBautopvf\fR \- convert from au to pvf format.
.SH "SYNOPSIS"
autopvf [options] [<aufile> [<pvffile>]]
.SH "DESCRIPTION"
\fIautopvf\fR converts from the au (Sun audio) format to the pvf (portable voice format) format.                                                        
.SH "OPTIONS"
autopvf can be called in the pipe mode:

	cat infile.au | autopvf [optons] > outfile.pvf

	autopvf [optons]infile.au | <second program>

or with two file names:

	autopvf [options] infile.au outfile.pvf

Valid options are:

\-h     brief help message

\-a     output pvf ascii format

\-b     output pvf binary format (default)

\-8     output 8 bit samples

\-16    output 16 bit samples

\-32    output 32 bit samples (default)

Usually there is no need for any of them.


.SH "SEE ALSO"
wavtopvf, lintopvf, voctopvf, basictopvf, rmdtopvf,
pvftoau, pvftowav, pvftolin, pvftovoc, pvftobasic, pvftormd
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
