.\" .IX pvf
.TH "lintopvf" "1" "1.4" "lintopvf" "PVF tools"
.SH "NAME"
\fBlintopvf\fR \- convert from linear headerless to PVF format.
.SH "SYNOPSIS"
basictopvf [options] [<linearfile> [<pvffile>]]
.SH "DESCRIPTION"
\fIlintopvf\fR converts from linear headerless samples to pvf (portable voice format) format.
.SH "OPTIONS"
lintopvf can be called in the pipe mode:

	cat infile | lintopvf [optons] > outfile.pvf

or with two file names:

	lintopvf [options] infile outfile.pvf

Valid options are:

\-h     brief help message

\-C     input 8 bit samples (default)

\-W     input 16 bit samples

\-U     input unsigned values (default)

\-S     input signed values

\-N     don't intput with intel byte order (default)

\-I     input with intel byte order

\-s <n> samples per second (default is 8000)

\-a     output pvf ascii format

\-b     output pvf binary format (default)

\-8     output 8 bit samples

\-16    output 16 bit samples

\-32    output 32 bit samples (default)

Usually there is no need for any of them.


.SH "SEE ALSO"
autopvf, basictopvf, wavtopvf, voctopvf, rmdtopvf,
pvftoau, pvftowav, pvftolin, pvftovoc, pvftobasic, pvftormd
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
