.TH pvf 1 "14 February 1997"
.IX pvf
.SH NAME
pvf tools \- utilities to convert various sound formats
.sp 0
.SH DESCRIPTION
The \fBpvf tools\fP are a collection of tools to convert vgetty modem data
to and from the 'raw modem data' format, and from that to and from various
audio file formats (like .au or .wav).  In addition, there are some tools
to manipulate pvf files, like speed up files or cut off trailing noise.

A list of commands is below in the "see also" section.

You can run those commands with the -h switch for available options. Please
also look at the individual contributed man pages.
.SH SEE ALSO
autopvf(1), basictopvf(1), lintopvf(1), pvf(1), pvfamp(1), pvfcut(1),
pvfecho(1), pvfff(1), pvffile(1), pvffilter(1), pvfmix(1), pvfnoise(1),
pvfreverse(1), pvfsine(1), pvfspeed(1), pvftoau(1), pvftobasic(1),
pvftolin(1), pvftormd(1), pvftovoc(1), pvftowav(1), rmdfile(1),
rmdtopvf(1), voctopvf(1), wavtopvf(1)

.SH AUTHOR
Original version from Klaus Weidner.
Copyright (C) 1997 by Marc Eberhard <Marc.Eberhard@Uni-Duesseldorf.DE>
