.\" .IX pvf
.TH "pvfamp" "1" "1.4" "pvfamp" "PVF tools"
.SH "NAME"
\fBpvfamp\fR \- pvf file amplitude adjustment.
.SH "SYNOPSIS"
pvfamp [options] [<pvffile in> [<pvffile out>]]
.SH "DESCRIPTION"
\fIpvfamp\fR increases or decreases the volume of the sound signal. Input and output is in the pvf (portable voice format) format.                         
.SH "OPTIONS"
pvfamp can be called in the pipe mode:

	cat infile.pvf | pvfamp [optons] > outfile.pvf

	pvfamp [options] infile.pvf | <program>

or with two file names:

	pvfamp [options] infile.pvf outfile.pvf

Valid options are:

\-h     brief help message

\-A <n> amplification factor (default is 1.0)
       n < 1 decreeses amplitude
       n > 1 increeses amplitude

\-a     output pvf ascii format

\-b     output pvf binary format (default)

\-8     output 8 bit samples

\-16    output 16 bit samples

\-32    output 32 bit samples (default)

Usually the \-A option is the only option needed.

.SH "EXAMPLES"
To double the volumn of a pvf file:

	pvfamp \-A 2 infile.pvf outfile.pvf

To convert a pdf file to a .wav file at 3/4 volumn:

	pvfamp \-A 0.75 infile.pvf | pvftowav > outfile.wav

.SH "SEE ALSO"
pvfcut, pvfecho, pvffft, pvffile, pvffilter, pvfmix, pvfnoise, pvfreverse, pvfsine, and pvfspeed
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
