.\" .IX pvf
.TH "pvfcut" "1" "1.5" "pvfcut" "PVF tools"
.SH "NAME"
\fBpvfcut\fR \- remove heading and/or trailing parts of voice files.
.SH "SYNOPSIS"
pvfcut [options] [<pvffile in> [<pvffile out>]]
.SH "DESCRIPTION"
\fIpvfcut\fR removes heading and/or trailing parts of a voice file. Input and output is in the pvf (portable voice format) format.
.SH "OPTIONS"
pvfcut can be called in the pipe mode:

	cat infile.pvf | pvfcut [optons] > outfile.pvf

	pvfcut [options] infile.pvf | <program>

or with two file names:

	pvfcut [options] infile.pvf outfile.pvf

Valid options are:

\-h     brief help message

\-H <n> seconds to remove from the start (default is 0.0)

\-T <n> seconds to remove from the end (default is 0.0)

\-a     output pvf ascii format

\-b     output pvf binary format (default)

\-8     output 8 bit samples

\-16    output 16 bit samples

\-32    output 32 bit samples (default)

You will normaly use the \-H and/or \-T option.
.SH "EXAMPLES"
To chop 1/2 second off the start of a pvf file.

	pvfcut \-H 0.5 infile.pvf outfile.pvf


To convert an incomming  voice message to pvf, and remove the last 2 seconds from the message
 
rmdtopvf message.rmd | pvfcut \-T 2.0 > message.pvf
.SH "SEE ALSO"
pvfamp, pvfecho, pvffft, pvffile, pvffilter, pvfmix, pvfnoise, pvfreverse, pvfsine, and pvfspeed
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
