.\" .IX pvf
.TH "pvfecho" "1" "1.5" "pvfecho" "PVF tools"
.SH "NAME"
\fBpvfecho\fR \- adds echo to sound signal.
.SH "SYNOPSIS"
pvfecho [options] [<pvffile in> [<pvffile out>]]
.SH "DESCRIPTION"
\fIpvfecho\fR adds echo to the sound signal. Input and output is in the pvf (portable voice format) format.
.SH "OPTIONS"
pvfecho can be called in the pipe mode:

	cat infile.pvf | pvfecho [optons] > outfile.pvf

	pvfecho [options] infile.pvf | <program>

or with two file names:

	pvfecho [options] infile.pvf outfile.pvf

Valid options are:

\-h     brief help message

\-A <n> echo volume factor (default is 0.3)

\-D <n> delay in seconds (default is 0.15)

\-a     output pvf ascii format

\-b     output pvf binary format (default)

\-8     output 8 bit samples

\-16    output 16 bit samples

\-32    output 32 bit samples (default)


Normaly, the only options you will need are \-A and \-D.

.SH "EXAMPLES"
To add the default echo to a pvf file:

	pvfecho infile.pvf outfile.pvf

.SH "SEE ALSO"
pvfamp, pvfcut, pvffft, pvffile, pvffilter, pvfmix, pvfnoise, pvfreverse, pvfsine, and pvfspeed
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
