.\" .IX pvf
.TH "pvffile" "1" "1.5" "pvffile" "PVF tools"
.SH "NAME"
\fBpvffile\fR prints out some useful information about .pvf files.
.SH "SYNOPSIS"
pvffile [options] [<pvffile>]

.SH "DESCRIPTION"
\fIpvffile\fR prints out some useful information about .pvf files.
.SH "OPTIONS"
pvffile [optons] [<infile.pvf>]

Valid options are:

\-h     brief help message

\-c     also print sample count
.SH "SEE ALSO"
pvfamp, pvfcut, pvfechot, pvfff, pvffilter, pvfmix, pvfnoise, pvfreverse, pvfsine, and pvfspeed
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
