.\" .IX pvf
.TH "pvffilter" "1" "1.2" "pvffilter" "PVF tools"
.SH "NAME"
\fBpvffilter\fR \- filters a range of frequencies.
.SH "SYNOPSIS"
pvffilter [options] [<pvffile in> [<pvffile out>]]

.SH "DESCRIPTION"
\fIpvffilter\fR can filter a range of frequencies out of a given voice signal.  Input and output is in the pvf (portable voice format) format.
.SH "OPTIONS"
pvffilter can be called in the pipe mode:

	cat infile.pvf | pvffilter [optons] > outfile.pvf

or with two file names:

	pvffilter [options] infile.pvf outfile.pvf

Valid options are:

\-h     brief help message

\-F <n> frequency of the filter in Hz (default is 1000)

\-W <n> width of the filter in Hz (default is 100)

\-a     output pvf ascii format

\-b     output pvf binary format (default)

\-8     output 8 bit samples

\-16    output 16 bit samples

\-32    output 32 bit samples (default)
.SH "SEE ALSO"
pvfamp, pvfcut, pvfechot, pvfff, pvffile, pvfmix, pvfnoise, pvfreverse, pvfsine, and pvfspeed
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
