.\" .IX pvf
.TH "pvffft" "1" "1.4" "pvffft" "PVF tools"
.SH "NAME"
\fBpvffft\fR \- does a fast fourier transformation.
.SH "SYNOPSIS"
pvffft [options] [<pvffile>]
.SH "DESCRIPTION"
\fIpvffft\fR does a fast fourier transformation of the input pvf samples and output the result in form of a table or decides, whether the input samples belong to a data call or to a voice call.
.SH "OPTIONS"
pvffft [optons] [<infile.pvf>]

Valid options are:

\-h     brief help message

\-H <n> seconds to remove from the start (default is 0.0)

\-N <n> number of samples to analyse (default is 1024)

\-T <n> threshold for the voice/data decision (default is 1.0)

\-P <n> vgetty pid (default is no pid) 

\-D     display fft table


.SH "SEE ALSO"
pvfamp, pvfcut, pvfechot, pvffile, pvffilter, pvfmix, pvfnoise, pvfreverse, pvfsine, and pvfspeed
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
