.\" .IX pvf
.TH "pvfnoise" "1" "1.1" "pvfnoise" "PVF tools"
.SH "NAME"
\fBpvfnoise\fR \- produces noise.  (Why?)
.SH "SYNOPSIS"
pvfnoise [options] [<pvffile in>]

.SH "DESCRIPTION"
\fIpvfnoise\fR   produces noise. Output is in the pvf (portable voice format) format.  If someone actualy uses this program, please let me know what it is used for.
.SH "OPTIONS"
Valid options are:

\-h     brief help message

\-L <n> length in seconds (default is 1.5)

\-s <n> samples per second (default is 8000)

\-a     output pvf ascii format

\-b     output pvf binary format (default)

\-8     output 8 bit samples

\-16    output 16 bit samples

\-32    output 32 bit samples (default)

.SH "SEE ALSO"
pvfamp, pvfcut, pvfechot, pvfff, pvffile, pvffilter, pvfmix, pvfreverse, pvfsine, and pvfspeed
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
