.\" .IX pvf
.TH "pvfreverse" "1" "1.5" "pvfreverse" "PVF tools"
.SH "NAME"
\fBpvfreversefR> \- reverses the voice file.
.SH "SYNOPSIS"
pvfreverse [options] [<pvffile in> [<pvffile out>]]

.SH "DESCRIPTION"
\fIpvfreverse\fR reverses the voice file (it plays it from end to start). Input and output is in the pvf (portable voice format) format.
.SH "OPTIONS"
pvfreverse can be called in the pipe mode:

	cat infile.pvf | pvfreverse [optons] > outfile.pvf

or with two file names:

	pvfreverse [options] infile.pvf outfile.pvf

Valid options are:

\-h     brief help message

\-a     output pvf ascii format

\-b     output pvf binary format (default)

\-8     output 8 bit samples

\-16    output 16 bit samples

\-32    output 32 bit samples (default)

You will normaly not need any options.
.SH "SEE ALSO"
pvfamp, pvfcut, pvfechot, pvfff, pvffile, pvffilter, pvfmix, pvfnoise, pvfsine, and pvfspeed
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
