.\" .IX pvf
.TH "pvfsine" "1" "1.4" "pvfsine" "PVF tools"
.SH "NAME"
\fBpvfsine\fR \- produces a simple sine wave.
.SH "SYNOPSIS"
pvfsine [options] [<pvffile in>]

.SH "DESCRIPTION"
\fIpvfsine\fR produces a simple sine wave. Output is in the pvf (portable voice format) format.
 
.SH "OPTIONS"
Valid options are:

\-h     brief help message

\-F <n> frequency in Hz (default is 933.0)

\-L <n> length in seconds (default is 1.5)

\-s <n> samples per second (default is 8000)

\-a     output pvf ascii format

\-b     output pvf binary format (default)

\-8     output 8 bit samples

\-16    output 16 bit samples

\-32    output 32 bit samples (default)

.SH "SEE ALSO"
pvfamp, pvfcut, pvfechot, pvfff, pvffile, pvffilter, pvfmix,  pvfnoise, pvfreverse, and pvfspeed
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
