.\" .IX pvf
.TH "pvftormd" "1" "1.11" "pvftormd" "PVF tools"
.SH "NAME"
\fBpvftormd\fR \- converts from pvf to rmd format.
.SH "SYNOPSIS"
pvftormd <modem type> <compression method> \\

[options] [<pvffile> [<rmdfile>]]
.SH "DESCRIPTION"
\fIpvftormd\fR converts from the pvf (portable voice format) format to  the rmd (raw modem data) format.
.SH "OPTIONS"
pvftormd can be called in the pipe mode:

	cat infile.pvf | pvftormd <modem type> \\

        <compression method> [optons] > outfile.rmd


or

	pvftormd <modem type> <compression method> \\

        [optons]infile.pvf | <second program>


or with two file names:

	pvftormd <modem type> <compression method> \\

        [options] infile.pvf outfile.rmd


Valid options are:

\-h     brief help message


\-L     list of supported raw modem data formats
       and compression methods

.SH "FORMATS"
Supported raw modem data formats:

 \- Digi           4 (G.711U) and 5 (G.711A)

 \- Elsa           2, 3 and 4 bit Rockwell ADPCM

 \- ISDN4Linux     2, 3 and 4 bit ZyXEL ADPCM

 \- Multitech 2834 4 bit IMA ADPCM

 \- Rockwell       2, 3 and 4 bit Rockwell ADPCM

 \- Rockwell       8 bit Rockwell PCM

 \- V253modem      8 bit PCM

 \- UMC            4 (G.721 ADPCM)

 \- US Robotics    1 and 4 (GSM and G.721 ADPCM

 \- ZyXEL 1496     2, 3 and 4 bit ZyXEL ADPCM

 \- ZyXEL 2864     2, 3 and 4 bit ZyXEL ADPCM

 \- ZyXEL Omni 56K 4 bit Digispeech ADPCM (?)

.SH "EXAMPLES"
To prepare a .wav file for use with a Rockwell modem:

	wavtopvf infile.wav | pvfspeed \-s 7200 | \\
	pvftormd Rockwell 4 > outfile.rmd

.SH "SEE ALSO"
pvftoau, pvftobasic, pvftolin,, pvftovoc, pvftowav, autopvf, basictopvf, lintopvf, rmdtopvf, voctopvf, and wavtopvf.
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
