.\" .IX pvf
.TH "pvftobasic" "1" "1.4" "pvftobasic" "PVF tools"
.SH "NAME"
\fBpvftobasic\fR \- converts from pvf to audio/basic format.
.SH "SYNOPSIS"
pvftobasic [options] [<pvffile> [<basicfile>]]
.SH "DESCRIPTION"
\fIpvftobasic\fR  converts from the pvf (portable voice format) format to the audio/basic format as defined in RFC 1521 (MIME) as the "absolutely minimal lowest common denominator audio format", which is 8\-bit ISDN uLaw (PCM) at a sampling rate of 8000 Hz.
.SH "OPTIONS"
pvftobasic can be called in the pipe mode:

	cat infile.pvf | pvftobasic [optons] > outfile

	pvftobasic [optons]infile.pvf | <second program>

or with two file names:

	pvftobasic [options] infile.pvf outfile

Valid options are:

\-h     brief help message
.SH "SEE ALSO"
pvftoau, pvftolin, pvftormd, pvftovoc, pvftowav, autopvf, basictopvf, lintopvf, rmdtopvf, voctopvf, and wavtopvf.
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
