.\" .IX pvf
.TH "pvftolin" "1" "1.4" "pvftolin" "PVF tools"
.SH "NAME"
\fBpvftolin\fR \- converts from pvf to linear format.
.SH "SYNOPSIS"
pvftolin [options] [<pvffile> [<linfile>]]
.SH "DESCRIPTION"
\fIpvftolin\fR converts from the pvf (portable voice format) format to linear headerless samples.
.SH "OPTIONS"
pvftolin can be called in the pipe mode:

	cat infile.pvf | pvftolin [optons] > outfile

	pvftolin [optons]infile.pvf | <second program>

or with two file names:

	pvftolin [options] infile.pvf outfile.au

Valid options are:

\-h     brief help message

\-C     output 8 bit samples (default)

\-W     output 16 bit samples

\-U     output unsigned values (default)

\-S     output signed values

.SH "SEE ALSO"
pvftoau, pvftobasic, pvftormd, pvftovoc, pvftowav, autopvf, basictopvf, lintopvf, rmdtopvf, voctopvf, and wavtopvf.
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
