.\" .IX pvf
.TH "pvftowav" "1" "1.4" "pvftowav" "PVF tools"
.SH "NAME"
\fBpvftowav\fR \- converts from pvf to wav format.
.SH "SYNOPSIS"
pvftowav [options] [<pvffile> [<wavfile>]]
.SH "DESCRIPTION"
\fIpvftowav\fR converts from the pvf (portable voice format) format to the Windows\-Format .wav.

.SH "OPTIONS"
pvftovoc can be called in the pipe mode:

	cat infile.pvf | pvftovoc [optons] > outfile.voc

	pvftovoc [optons]infile.pvf | <second program>

or with two file names:

	pvftovoc [options] infile.pvf outfile.voc

Valid options are:

\-h     brief help message

\-8     output  8 bit samples (default)

\-16    output 16 bit samples

\-32    output 32 bit samples

.SH "EXAMPLES"
Play a rmd file using play command from SOX.

	rmdtopvf rmdfile | pvftowav | play \-t .wav \-

.SH "SEE ALSO"
pvftoau, pvftobasic, pvftolin, pvftormd, pvftovoc, autopvf, basictopvf, lintopvf, rmdtopvf, voctopvf, and wavtopvf.
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
