.\" .IX pvf
.TH "pvftoau" "1" "1.4" "pvftoau" "PVF tools"
.SH "NAME"
\fBpvftoau\fR \- converts from pvf to au format.
.SH "SYNOPSIS"
pvftoau [options] [<pvffile> [<aufile>]]
.SH "DESCRIPTION"
\fIpvftoau\fR converts from the pvf (portable voice format) format to the au (Sun audio) format.
.SH "OPTIONS"
pvftoau can be called in the pipe mode:

	cat infile.pvf | pvftoau [optons] > outfile.au

	pvftoau [optons]infile.pvf | <second program>

or with two file names:

	pvftoau [options] infile.pvf outfile.au

Valid options are:

\-h     brief help message

\-U     output 8\-bit uLaw (default)

\-8     output 8\-bit linear

\-16    output 16\-bit linear

.SH "EXAMPLES"
Play a rmd file by dumping it directly do /dev/audio:

	rmdtopvf rmdfile | pvftoau > /dev/audio

.SH "SEE ALSO"
pvftobasic, pvftolin, pvftormd, pvftovoc, pvftowav, autopvf, basictopvf, lintopvf, rmdtopvf, voctopvf, and wavtopvf.
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
