.\" .IX pvf
.TH "pvftovoc" "1" "1.4" "pvftovoc" "PVF tools"
.SH "NAME"
\fBpvftovoc\fR \- converts from pvf to voc format.
.SH "SYNOPSIS"
pvftovoc [options] [<pvffile> [<vocfile>]]
.SH "DESCRIPTION"
\fIpvftovoc\fR converts from the pvf (portable voice format) format to the voc (Creativ voice file) format.
.SH "OPTIONS"
pvftovoc can be called in the pipe mode:

	cat infile.pvf | pvftovoc [optons] > outfile.voc

	pvftovoc [optons]infile.pvf | <second program>

or with two file names:

	pvftovoc [options] infile.pvf outfile.voc

Valid options are:

\-h     brief help message
.SH "SEE ALSO"
pvftoau, pvftobasic, pvftolin, pvftormd, pvftowav, autopvf, basictopvf, lintopvf, rmdtopvf, voctopvf, and wavtopvf.
.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
