.\" .IX pvf
.TH "rmdfile" "1" "1.4" "rmdfile" "PVF tools"
.SH "NAME"
\fBrmdfile\fR \- prints out some useful information about .rmd files
.SH "SYNOPSIS"
rmdfile [options] [<rmdfile in>]

.SH "DESCRIPTION"
\fIrmdfile\fR  prints out some useful information about .rmd (raw modem data) files.
.SH "OPTIONS"
Valid options are:

\-h     brief help message

.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
