.\" .IX pvf
.TH "rmdtopvf" "1" "1.4" "rmdtopvf" "PVF tools"
.SH "NAME"
\fBrmdtopvf\fR \- convert from RMD to PVF format.
.SH "SYNOPSIS"
rmdtopvf [options] [<rmdfile> [<pvffile>]]
.SH "DESCRIPTION"
\fIrmdtopvf\fR converts from the rmd (raw modem data) format to the pvf (portable voice format) format.
.SH "OPTIONS"
rmdtopvf can be called in the pipe mode:

	cat infile.rmd | rmdtopvf [optons] > outfile.pvf

or with two file names:

	rmdtopvf [options] infile.rmd outfile.pvf

Valid options are:

\-h     brief help message

\-L     list of supported raw modem data formats

\-a     output pvf ascii format

\-b     output pvf binary format (default)

\-8     output 8 bit samples

\-16    output 16 bit samples

\-32    output 32 bit samples (default)


Usually there is no need for any of them.


.SH "FORMATS"
Supported raw modem data formats:

 \- Digi           4 (G.711U) and 5 (G.711A)

 \- Elsa           2, 3 and 4 bit Rockwell ADPCM

 \- ISDN4Linux     2, 3 and 4 bit ZyXEL ADPCM

 \- Multitech 2834 4 bit IMA ADPCM

 \- Rockwell       2, 3 and 4 bit Rockwell ADPCM

 \- Rockwell       8 bit Rockwell PCM

 \- V253modem      8 bit PCM

 \- UMC            4 (G.721 ADPCM)

 \- US Robotics    1 and 4 (GSM and G.721 ADPCM

 \- ZyXEL 1496     2, 3 and 4 bit ZyXEL ADPCM

 \- ZyXEL 2864     2, 3 and 4 bit ZyXEL ADPCM

 \- ZyXEL Omni 56K 4 bit Digispeech ADPCM (?)

.SH "SEE ALSO"
autopvf, lintopvf, voctopvf, basictopvf, wavtopvf, pvftoau, pvftowav, pvftolin, pvftovoc, pvftobasic, and pvftormd.
.SH "EXAMPLES"
Play a rmd file using play from the SOX package:

	rmdtopvf rmdfile | pvftowav | play \-t .wav \-


Play a rmd file by dumping it directly to /dev/audio:

	rmdtopvf rmdfile | pvftoau > /dev/audio

.SH "AUTHOR"
Mikkel L. Ellertson <mikkel@infinity\-ltd.com>
