.TH zplay 1 "30 December 1995"
.IX zplay
.SH NAME
zplay \- modem utility to record and play voice files
.sp 0
.SH DESCRIPTION
\fBzplay\fP is obsolete. Please use the new \fBvm\fP utility instead.
.SH AUTHOR
Original version from Klaus Weidner.
Copyright (C) 1995 by Marc Eberhard <Marc.Eberhard@Uni-Duesseldorf.DE>
