# Makefile -- Build instructions for Midas lab RTE-V850E/ME2-CB eval board
#
#  Copyright (C) 2003  NEC Electronics Corporation
#  Copyright (C) 2003  Miles Bader <miles@gnu.org>
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# Written by Miles Bader <miles@gnu.org>

PLATFORM_DEVICES = ttyS0,c,4,64 ttyS1,c,4,65 leds,c,10,169 ppp,c,108,0

include $(NEC_COMMON)/embedded-root.mk
