.\" -*- nroff -*-
.\" Copyright 1999 by David S. Miller.  All Rights Reserved.
.\" Portions Copyright 2001 Sun Microsystems
.\" This file may be copied under the terms of the GNU Public License.
.\" 
.\"	.An - list of n alternative values as in "flav vanilla|strawberry"
.\"
.de A1
\\fB\\$1\\fP|\\fB\\$2\\fP
..
.de A2
\\fB\\$1\\fP\ \\fB\\$2\\fP|\\fB\\$3\\fP
..
.de A3
\\fB\\$1\\fP\ \\fB\\$2\\fP|\\fB\\$3\\fP|\\fB\\$4\\fP
..
.de A4
\\fB\\$1\\fP\ \\fB\\$2\\fP|\\fB\\$3\\fP|\\fB\\$4\\fP|\\fB\\$5\\fP
..
.\" 
.\"	.Bn - same as above but framed by square brackets
.\"
.de B1
[\\fB\\$1\\fP|\\fB\\$2\\fP]
..
.de B2
[\\fB\\$1\\fP\ \\fB\\$2\\fP|\\fB\\$3\\fP]
..
.de B3
[\\fB\\$1\\fP\ \\fB\\$2\\fP|\\fB\\$3\\fP|\\fB\\$4\\fP]
..
.de B4
[\\fB\\$1\\fP\ \\fB\\$2\\fP|\\fB\\$3\\fP|\\fB\\$4\\fP|\\fB\\$5\\fP]
..
.\"
.\"	\(*MA - mac address
.\"
.ds MA \fIxx\fP\fB:\fP\fIyy\fP\fB:\fP\fIzz\fP\fB:\fP\fIaa\fP\fB:\fP\fIbb\fP\fB:\fP\fIcc\fP
.\"
.\"	\(*WO - wol flags
.\"
.ds WO \fBp\fP|\fBu\fP|\fBm\fP|\fBb\fP|\fBa\fP|\fBg\fP|\fBs\fP|\fBd\fP...
.TH ETHTOOL 8 "September 2006" "Ethtool version 5"
.SH NAME
ethtool \- Display or change ethernet card settings
.SH SYNOPSIS
.B ethtool
.I ethX

.B ethtool \-h|\-\-help

.B ethtool \-a|\-\-show\-pause
.I ethX

.B ethtool \-A|\-\-pause
.I ethX
.B2 autoneg on off
.B2 rx on off
.B2 tx on off

.B ethtool \-c|\-\-show\-coalesce
.I ethX

.B ethtool \-C|\-\-coalesce
.I ethX
.B2 adaptive-rx on off
.B2 adaptive-tx on off
.RB [ rx-usecs
.IR N ]
.RB [ rx-frames
.IR N ]
.RB [ rx-usecs-irq
.IR N ]
.RB [ rx-frames-irq
.IR N ]
.RB [ tx-usecs
.IR N ]
.RB [ tx-frames
.IR N ]
.RB [ tx-usecs-irq
.IR N ]
.RB [ tx-frames-irq
.IR N ]
.RB [ stats-block-usecs
.IR N ]
.RB [ pkt-rate-low
.IR N ]
.RB [ rx-usecs-low
.IR N ]
.RB [ rx-frames-low
.IR N ]
.RB [ tx-usecs-low
.IR N ]
.RB [ tx-frames-low
.IR N ]
.RB [ pkt-rate-high
.IR N ]
.RB [ rx-usecs-high
.IR N ]
.RB [ rx-frames-high
.IR N ]
.RB [ tx-usecs-high
.IR N ]
.RB [ tx-frames-high
.IR N ]
.RB [ sample-interval
.IR N ]

.B ethtool \-g|\-\-show\-ring
.I ethX

.B ethtool \-G|\-\-set\-ring
.I ethX
.RB [ rx
.IR N ]
.RB [ rx-mini
.IR N ]
.RB [ rx-jumbo
.IR N ]
.RB [ tx
.IR N ]

.B ethtool \-i|\-\-driver
.I ethX

.B ethtool \-d|\-\-register\-dump
.I ethX
.B2 raw on off

.B ethtool \-e|\-\-eeprom\-dump
.I ethX
.B2 raw on off
.RB [ offset
.IR N ]
.RB [ length
.IR N ]

.B ethtool \-E|\-\-change\-eeprom
.I ethX
.RB [ magic
.IR N ]
.RB [ offset
.IR N ]
.RB [ value
.IR N ]

.B ethtool \-k|\-\-show\-offload
.I ethX

.B ethtool \-K\-\-offload
.I ethX
.B2 rx on off
.B2 tx on off
.B2 sg on off
.B2 tso on off
.B2 ufo on off
.B2 gso on off

.B ethtool \-p|\-\-blink
.I ethX
.IR [ N ]

.B ethtool \-r|\-\-negotiate
.I ethX

.B ethtool \-S|\-\-statistics
.I ethX

.B ethtool \-t|\-\-test
.I ethX
.B1 offline online

.B ethtool \-s
.I ethX
.B3 speed 10 100 1000
.B2 duplex half full
.B4 port tp aui bnc mii fibre
.B2 autoneg on off
.RB [ phyad
.IR N ]
.B2 xcvr internal external
.RB [ wol \ \*(WO]
.RB [ sopass \ \*(MA]
.RB [ msglvl
.IR N ]
.SH DESCRIPTION
.BI ethtool
is used for querying settings of an ethernet device and changing them.

.I ethX
is the name of the ethernet device to work on.

.SH OPTIONS
.B ethtool
with a single argument specifying the device name prints current
setting of the specified device.
.TP
.B \-h \-\-help
shows a short help message.
.TP
.B \-a \-\-show\-pause
queries the specified ethernet device for pause parameter information.
.TP
.B \-A \-\-pause
change the pause parameters of the specified ethernet device.
.TP
.A2 autoneg on off
Specify if pause autonegotiation is enabled.
.TP
.A2 rx on off
Specify if RX pause is enabled.
.TP
.A2 tx on off
Specify if TX pause is enabled.
.TP
.B \-c \-\-show\-coalesce
queries the specified ethernet device for coalescing information.
.TP
.B \-C \-\-coalesce
change the coalescing settings of the specified ethernet device.
.TP
.B \-g \-\-show\-ring
queries the specified ethernet device for rx/tx ring parameter information.
.TP
.B \-G \-\-set\-ring
change the rx/tx ring parameters of the specified ethernet device.
.TP
.BI rx \ N
Change number of ring entries for the Rx ring.
.TP
.BI rx-mini \ N
Change number of ring entries for the Rx Mini ring.
.TP
.BI rx-jumbo \ N
Change number of ring entries for the Rx Jumbo ring.
.TP
.BI tx \ N
Change number of ring entries for the Tx ring.
.TP
.B \-i \-\-driver
queries the specified ethernet device for associated driver information.
.TP
.B \-d \-\-register\-dump
retrieves and prints a register dump for the specified ethernet device.
When raw is enabled, then it dumps the raw register data to stdout.
.TP
.B \-e \-\-eeprom\-dump
retrieves and prints an EEPROM dump for the specified ethernet device.
When raw is enabled, then it dumps the raw EEPROM data to stdout. The
length and offset parameters allow dumping certain portions of the EEPROM.
Default is to dump the entire EEPROM.
.TP
.B \-E \-\-change\-eeprom
Changes EEPROM byte for the specified ethernet device.  offset and value
specify which byte and it's new value.  Because of the persistent nature
of writing to the EEPROM, a device-specific magic key must be specified
to prevent the accidental writing to the EEPROM.
.TP
.B \-k \-\-show\-offload
queries the specified ethernet device for offload information.
.TP
.B \-K \-\-offload
change the offload parameters of the specified ethernet device.
.TP
.A2 rx on off
Specify if RX checksumming is enabled.
.TP
.A2 tx on off
Specify if TX checksumming is enabled.
.TP
.A2 sg on off
Specify if scatter-gather is enabled.
.TP
.A2 tso on off
Specify if tcp segmentation offload is enabled.
.TP
.A2 ufo on off
Specify if UDP fragmentation offload is enabled 
.TP
.A2 gso on off
Specify if generic segmentation offload is enabled 
.TP
.B \-p \-\-identify
initiates adapter-specific action intended to enable an operator to
easily identify the adapter by sight.  Typically this involves
blinking one or more LEDs on the specific ethernet port.
.TP
.B N
Length of time to perform phys-id, in seconds.
.TP
.B \-r \-\-negotiate
restarts auto-negotiation on the specified ethernet device, if
auto-negotiation is enabled.
.TP
.B \-S \-\-statistics
queries the specified ethernet device for NIC- and driver-specific
statistics.
.TP
.B \-t \-\-test
executes adapter selftest on the specified ethernet device. Possible test modes are:
.TP
.A1 offline online
defines test type: 
.B offline
(default) means to perform full set of tests possibly causing normal operation interruption during the tests,
.B online
means to perform limited set of tests do not interrupting normal adapter operation.
.TP
.B \-s \-\-change
option allows changing some or all settings of the specified ethernet device.
All following options only apply if
.B \-s
was specified.
.TP
.A3 speed 10 100 1000
Set speed in Mb/s.
.B ethtool
with single argument will show you the supported device speeds.
.TP
.A2 duplex half full
Set full or half duplex mode.
.TP
.A4 port tp aui bnc mii fibre
Select device port.
.TP
.A2 autoneg on off
Specify if autonegotiation is enabled. In the usual case it is, but might
cause some problems with some network devices, so you can turn it off.
.TP
.BI phyad \ N
PHY address.
.TP
.A2 xcvr internal external
Select transceiver type. Currently only internal and external can be
specified, in the future further types might be added.
.TP
.BR wol \ \*(WO
Set Wake-on-LAN options.  Not all devices support this.  The argument to 
this option is a string of characters specifying which options to enable.
.RS
.PD 0
.TP 3
.B p
Wake on phy activity
.TP 3
.B u
Wake on unicast messages
.TP 3
.B m
Wake on multicast messages
.TP 3
.B b
Wake on broadcast messages
.TP 3
.B a
Wake on ARP
.TP 3
.B g
Wake on MagicPacket(tm)
.TP 3
.B s
Enable SecureOn(tm) password for MagicPacket(tm)
.TP 3
.B d
Disable (wake on nothing).  This option clears all previous options.
.PD
.RE
.TP
.B sopass \*(MA\c
Set the SecureOn(tm) password.  The argument to this option must be 6
bytes in ethernet MAC hex format (\*(MA).
.TP
.BI msglvl \ N
Set the driver message level. Meanings differ per driver.
.SH BUGS
Not supported (in part or whole) on all ethernet drivers.
.SH AUTHOR
.B ethtool
was written by David Miller.

Modifications by 
Jeff Garzik, 
Tim Hockin,
Jakub Jelinek,
Andre Majorel,
Eli Kupermann,
Scott Feldman,
Andi Kleen.
.SH AVAILABILITY
.B ethtool
is available over the Web on the SourceForge site at
http://sourceforge.net/projects/gkernel/

